import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, Copy, Eye, EyeOff, Plus, RotateCw, Save, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useForm, type UseFormReturn } from 'react-hook-form'
import { useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { toast } from 'sonner'
import { z } from 'zod'
import { Alert } from '@/components/ui/alert'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Form } from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Separator } from '@/components/ui/separator'
import { Switch } from '@/components/ui/switch'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Textarea } from '@/components/ui/textarea'
import { apiFetch, APIError } from '../../api/client'
import type { RedactedProjectConfiguration, RedactedSecretInput, UpdateSecretInput } from '../../api/types'
import { OperationPanel } from '../operations/OperationPanel'
import { defaultConfiguration, OAUTH_PROVIDERS, specialFields } from '../projects/projectSchema'

const SECTIONS = ['general', 'services', 'auth', 'smtp', 'oauth', 'storage', 'realtime', 'functions', 'database', 'pooler', 'network', 'secrets'] as const
type Section = typeof SECTIONS[number]
type Snapshot = { projectId: string; revision: number; lastGoodRevision: number; configuration: RedactedProjectConfiguration }
type PendingSave = { section: Section; value: unknown; labels: string[]; services: string[] }

/** The installed project has one configuration workspace. Every legacy section is a query selection, not a second form. */
export function ConfigurationPage() {
  const { projectId = '' } = useParams()
  const [params, setParams] = useSearchParams()
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const requested = params.get('section') ?? 'general'
  const section: Section = (SECTIONS as readonly string[]).includes(requested) ? requested as Section : 'general'
  useEffect(() => { if (requested !== section) { const next = new URLSearchParams(params); next.set('section', section); setParams(next, { replace: true }) } }, [params, requested, section, setParams])
  const configuration = useQuery({ queryKey: ['project-configuration', projectId], queryFn: () => apiFetch<Snapshot>(`/api/projects/${projectId}/configuration`), enabled: Boolean(projectId) })
  const form = useForm<RedactedProjectConfiguration>({ resolver: zodResolver(configurationUpdateSchema) as any, defaultValues: defaultConfiguration('LIGHTWEIGHT') as RedactedProjectConfiguration })
  const [pending, setPending] = useState<PendingSave>()
  const [operation, setOperation] = useState<{ projectId: string; operationId: string }>()
  const [conflict, setConflict] = useState(false)

  useEffect(() => { if (configuration.data && !form.formState.isDirty) form.reset(configuration.data.configuration) }, [configuration.data, form])

  const save = useMutation({
    mutationFn: async (input: PendingSave) => {
      const expectedRevision = configuration.data?.revision ?? form.getValues('revision')
      const body = { expectedRevision, value: input.value }
      return apiFetch<{ projectId: string; operationId: string; revision: number }>(`/api/projects/${projectId}/configuration/${input.section}`, { method: 'PATCH', body: JSON.stringify(body) })
    },
    onSuccess: (result) => { setPending(undefined); setOperation({ projectId: result.projectId, operationId: result.operationId }); setConflict(false); toast.success('Configuration update queued') },
    onError: (error) => { if (error instanceof APIError && error.status === 409) setConflict(true); if (error instanceof APIError && error.fields) for (const [path, message] of Object.entries(error.fields)) form.setError(path as never, { type: 'server', message }); toast.error(error.message) },
  })
  const reload = async () => { setConflict(false); setPending(undefined); const result = await configuration.refetch(); if (result.data) form.reset(result.data.configuration) }
  const submit = (value: unknown, labels: string[], services: string[]) => setPending({ section, value, labels, services })
  const onSucceeded = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['project-configuration', projectId] }), queryClient.invalidateQueries({ queryKey: ['project', projectId] })]); setOperation(undefined) }

  if (configuration.isLoading) return <main className="page"><div className="empty-state">Loading configuration…</div></main>
  if (configuration.error || !configuration.data) return <main className="page"><Alert variant="destructive">Unable to load project configuration.</Alert></main>
  if (operation) return <main className="page configuration-page"><div className="page-heading"><div><p className="eyebrow">Configuration operation</p><h1>Applying project configuration</h1><p className="muted">The runtime is reconciled in the background. This panel remains available until completion.</p></div></div><OperationPanel operationId={operation.operationId} projectId={projectId} projectName={projectId} onSucceeded={onSucceeded} /></main>

  return <main className="page configuration-page">
    <div className="page-heading"><div><p className="eyebrow">Installed project</p><h1>Configuration</h1><p className="muted">Typed settings for this project. Secrets remain encrypted and redacted.</p></div><Badge variant="outline">Revision {configuration.data.revision}</Badge></div>
    {conflict && <Alert variant="destructive" className="mb-4"><div className="flex items-center justify-between gap-3"><span>This configuration is stale. Your dirty fields are preserved.</span><Button size="sm" variant="outline" onClick={() => void reload()}>Reload</Button></div></Alert>}
    <FormLayout section={section} setSection={(value) => navigate(`/projects/${projectId}/configuration?section=${value}`)} />
    <Form {...form}><form onSubmit={(event) => event.preventDefault()}>
      <Tabs value={section} onValueChange={(value) => navigate(`/projects/${projectId}/configuration?section=${value}`)}>
        <TabsList className="grid w-full grid-cols-3 gap-1 md:grid-cols-6 xl:grid-cols-12"><Tab name="general" label="General" /><Tab name="services" label="Services" /><Tab name="auth" label="Auth" /><Tab name="smtp" label="Email & SMTP" /><Tab name="oauth" label="OAuth" /><Tab name="storage" label="Storage" /><Tab name="realtime" label="Realtime" /><Tab name="functions" label="Functions" /><Tab name="database" label="Database" /><Tab name="pooler" label="Pooler" /><Tab name="network" label="Network" /><Tab name="secrets" label="API & Secrets" /></TabsList>
        <TabsContent value={section} className="mt-4"><SectionForm section={section} projectId={projectId} form={form} onSave={submit} /></TabsContent>
      </Tabs>
    </form></Form>
    <div className="mt-4 flex justify-end"><Button onClick={() => void form.handleSubmit(() => submitSection(form, section, submit), () => undefined)()} disabled={save.isPending}><Save className="size-4" />Save {sectionLabel(section)}</Button></div>
    <AlertDialog open={!!pending} onOpenChange={(open) => !open && setPending(undefined)}>
      <AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Apply configuration changes?</AlertDialogTitle><AlertDialogDescription>These changes will be validated and applied as a durable runtime operation.</AlertDialogDescription></AlertDialogHeader>
        {pending && <div className="space-y-3 text-sm"><div><strong>Changed settings</strong><ul className="mt-1 list-disc pl-5">{pending.labels.map((label) => <li key={label}>{label}</li>)}</ul></div><div><strong>Affected services</strong><p className="mt-1 text-muted-foreground">{pending.services.join(', ') || 'Configuration metadata only'}</p></div><Badge variant="outline">{pending.services.length ? 'Service restart/recreate may be required' : 'No runtime restart expected'}</Badge></div>}
        <AlertDialogFooter><AlertDialogCancel>Keep editing</AlertDialogCancel><AlertDialogAction onClick={() => pending && save.mutate(pending)}>Confirm and apply</AlertDialogAction></AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  </main>
}

function Tab({ name, label }: { name: string; label: string }) { return <TabsTrigger value={name}>{label}</TabsTrigger> }
function FormLayout({ section, setSection }: { section: Section; setSection: (section: Section) => void }) { return <span className="sr-only" aria-live="polite">Editing {sectionLabel(section)}<button type="button" onClick={() => setSection('general')}>Configuration workspace</button></span> }
function sectionLabel(section: Section) { return section === 'smtp' ? 'Email & SMTP' : section === 'oauth' ? 'OAuth Providers' : section === 'pooler' ? 'Connection Pooler' : section === 'secrets' ? 'API & Secrets' : section[0].toUpperCase() + section.slice(1) }

function SectionForm({ section, projectId, form, onSave }: { section: Section; projectId: string; form: UseFormReturn<RedactedProjectConfiguration>; onSave: (value: unknown, labels: string[], services: string[]) => void }) {
  switch (section) {
    case 'general': return <GeneralSection form={form} />
    case 'services': return <ServicesSection form={form} />
    case 'auth': return <AuthSection form={form} />
    case 'smtp': return <SMTPSection form={form} />
    case 'oauth': return <OAuthSection form={form} />
    case 'storage': return <StorageSection form={form} />
    case 'realtime': return <RealtimeSection form={form} />
    case 'functions': return <FunctionsSection form={form} />
    case 'database': return <DatabaseSection projectId={projectId} form={form} />
    case 'pooler': return <PoolerSection form={form} />
    case 'network': return <NetworkSection form={form} />
    case 'secrets': return <SecretsSection projectId={projectId} />
  }
}

function submitSection(form: UseFormReturn<RedactedProjectConfiguration>, section: Section, submit: (value: unknown, labels: string[], services: string[]) => void) {
  const value = structuredClone(form.getValues(section as any) as unknown)
  const labels = dirtyLabels(form.formState.dirtyFields as Record<string, unknown>, section)
  const services = sectionServices(section)
  submit(normalizeUpdateSection(section, value), labels.length ? labels : [sectionLabel(section)], services)
}
function dirtyLabels(value: Record<string, unknown>, prefix: string, path: string[] = []): string[] { const result: string[] = []; for (const [key, child] of Object.entries(value)) { if (!child) continue; const next = [...path, key]; if (child === true || (typeof child === 'object' && child && ('type' in child || 'message' in child))) result.push(next.join('.')); else if (typeof child === 'object') result.push(...dirtyLabels(child as Record<string, unknown>, prefix, next)) } return result.filter((item) => item !== prefix) }
function sectionServices(section: Section) { const values: Record<Section, string[]> = { general: ['gateway', 'auth'], services: ['runtime'], auth: ['auth'], smtp: ['auth'], oauth: ['auth'], storage: ['storage', 'postgrest'], realtime: ['realtime'], functions: ['functions'], database: ['postgres'], pooler: ['supavisor'], network: ['gateway'], secrets: [] }; return values[section] }

function normalizeUpdateSection(section: Section, value: unknown): unknown {
  if (section === 'auth' && value && typeof value === 'object') { const auth: any = structuredClone(value); auth.smtp.password = explicitSecret(auth.smtp.password, auth.smtp.passwordSet); auth.phone.secret = explicitSecret(auth.phone.secret, auth.phone.secretSet); for (const key of Object.keys(auth.oauth ?? {})) { const item = auth.oauth[key]; item.secret = explicitSecret(item.secret, item.secretSet); } return auth }
  if (section === 'smtp' && value && typeof value === 'object') { const smtp: any = structuredClone(value); smtp.password = explicitSecret(smtp.password, smtp.passwordSet); return smtp }
  if (section === 'oauth' && value && typeof value === 'object') { const oauth: any = structuredClone(value); for (const key of Object.keys(oauth ?? {})) oauth[key].secret = explicitSecret(oauth[key].secret, oauth[key].secretSet); return oauth }
  if (section === 'storage' && value && typeof value === 'object') { const storage: any = structuredClone(value); storage.secretAccessKey = explicitSecret(storage.secretAccessKey, storage.secretAccessKeySet); return storage }
  if (section === 'functions' && value && typeof value === 'object') { const functions: any = structuredClone(value); functions.variables = functions.variables?.map((item: any) => ({ ...item, value: explicitSecret(item.value, item.valueSet) })); return functions }
  return value
}
function explicitSecret(secret: RedactedSecretInput, configured: boolean): UpdateSecretInput { return configured && secret.action === '' ? { action: 'retain' } : secret }

function GeneralSection({ form }: { form: UseFormReturn<RedactedProjectConfiguration> }) { const general = form.watch('general'); return <Card><SectionHeader title="General" description="Public identity and pinned runtime version." /><CardContent className="grid gap-5 md:grid-cols-2"><TextField form={form} name="general.domain" label="Domain" /><TextField form={form} name="general.siteUrl" label="Site URL" /><Field><FieldLabel>Supabase version</FieldLabel><Input value={general.supabaseVersion} readOnly /></Field><Field><FieldLabel>Project URL</FieldLabel><Input value={general.domain ? `https://${general.domain}` : 'Derived after domain is set'} readOnly /><FieldDescription>Generated from the project domain.</FieldDescription></Field><Field><FieldLabel>OAuth callback base URL</FieldLabel><Input value={general.siteUrl ? `${general.siteUrl.replace(/\/$/, '')}/auth/v1/callback` : 'Derived from Site URL'} readOnly /></Field></CardContent></Card> }
function ServicesSection({ form }: { form: UseFormReturn<RedactedProjectConfiguration> }) { const services = form.watch('services'); return <Card><SectionHeader title="Services" description="Enable optional services. Required dependencies are enforced together." /><CardContent className="grid gap-3 md:grid-cols-2">{Object.entries(services).map(([name, value]) => <Toggle key={name} label={serviceName(name)} checked={value} onChange={(next) => form.setValue(`services.${name}` as any, next, { shouldDirty: true, shouldValidate: true })} disabled={['database', 'gateway', 'auth', 'rest', 'studio', 'postgresMeta'].includes(name)} description={name === 'database' ? 'PostgreSQL is required.' : undefined} />)}</CardContent></Card> }
function AuthSection({ form }: { form: UseFormReturn<RedactedProjectConfiguration> }) { const auth = form.watch('auth'); return <Card><SectionHeader title="Authentication" description="Auth policy, signup/session controls, redirects and phone authentication." /><CardContent className="space-y-6"><FieldGroup className="grid gap-3 md:grid-cols-2"><Toggle label="Auth service" checked={auth.enabled} onChange={(next) => { form.setValue('auth.enabled', next, { shouldDirty: true }); form.setValue('services.auth', next, { shouldDirty: true }) }} /><Toggle label="Email Auth" checked={auth.email.enabled} onChange={(next) => form.setValue('auth.email.enabled', next, { shouldDirty: true })} /><Toggle label="Allow signup" checked={auth.email.allowSignup} onChange={(next) => { form.setValue('auth.email.allowSignup', next, { shouldDirty: true }); form.setValue('auth.disableSignup', !next, { shouldDirty: true }) }} /><Toggle label="Confirm email" checked={auth.email.confirmEmail} onChange={(next) => form.setValue('auth.email.confirmEmail', next, { shouldDirty: true })} /><Toggle label="Secure email change" checked={auth.email.secureEmailChange} onChange={(next) => { form.setValue('auth.email.secureEmailChange', next, { shouldDirty: true }); form.setValue('auth.email.doubleConfirmChanges', next, { shouldDirty: true }) }} /><Toggle label="Double confirm changes" checked={auth.email.doubleConfirmChanges} onChange={(next) => { form.setValue('auth.email.doubleConfirmChanges', next, { shouldDirty: true }); form.setValue('auth.email.secureEmailChange', next, { shouldDirty: true }) }} /><Toggle label="Anonymous sign-in" checked={auth.anonymousSignIn} onChange={(next) => form.setValue('auth.anonymousSignIn', next, { shouldDirty: true })} /><NumberField form={form} name="auth.jwtExpiry" label="JWT expiry (seconds)" /></FieldGroup><Field><FieldLabel>Redirect URLs</FieldLabel><FieldDescription>One absolute http(s) URL per line.</FieldDescription><Textarea value={auth.redirectUrls?.join('\n') ?? ''} onChange={(event) => form.setValue('auth.redirectUrls', event.target.value.split(/\n/).map((v) => v.trim()).filter(Boolean), { shouldDirty: true })} /></Field><Separator /><Collapsible><CollapsibleTrigger className="text-sm font-medium">Advanced Auth settings</CollapsibleTrigger><CollapsibleContent className="pt-4"><PhoneFields form={form} /></CollapsibleContent></Collapsible></CardContent></Card> }
function PhoneFields({ form }: { form: UseFormReturn<RedactedProjectConfiguration> }) { const phone = form.watch('auth.phone'); return <div className="space-y-4"><Toggle label="Phone Auth" checked={phone.enabled} onChange={(next) => form.setValue('auth.phone.enabled', next, { shouldDirty: true })} /><Field><FieldLabel>Provider</FieldLabel><Select value={phone.provider || undefined} onValueChange={(value) => value && form.setValue('auth.phone.provider', value, { shouldDirty: true })}><SelectTrigger><SelectValue placeholder="Choose provider" /></SelectTrigger><SelectContent><SelectItem value="twilio">Twilio</SelectItem><SelectItem value="messagebird">MessageBird</SelectItem><SelectItem value="textlocal">Textlocal</SelectItem></SelectContent></Select></Field>{phone.provider && <SecretEditor label="Provider secret" secret={phone.secret} configured={phone.secretSet} onChange={(value) => form.setValue('auth.phone.secret', value, { shouldDirty: true })} />}</div> }
function SMTPSection({ form }: { form: UseFormReturn<RedactedProjectConfiguration> }) { const smtp = form.watch('auth.smtp'); return <Card><SectionHeader title="Email & SMTP" description="Custom SMTP is write-only; an empty configured value means retain until changed." /><CardContent className="space-y-5"><Toggle label="Enable custom SMTP" checked={smtp.enabled} onChange={(next) => form.setValue('auth.smtp.enabled', next, { shouldDirty: true })} /><FieldGroup className="grid gap-4 md:grid-cols-2"><TextField form={form} name="auth.smtp.host" label="Host" /><NumberField form={form} name="auth.smtp.port" label="Port" /><TextField form={form} name="auth.smtp.username" label="Username" /><SecretEditor label="Password" secret={smtp.password} configured={smtp.passwordSet} onChange={(value) => form.setValue('auth.smtp.password', value, { shouldDirty: true })} /><TextField form={form} name="auth.smtp.senderEmail" label="Sender email" /><TextField form={form} name="auth.smtp.senderName" label="Sender name" /></FieldGroup></CardContent></Card> }
function OAuthSection({ form }: { form: UseFormReturn<RedactedProjectConfiguration> }) { const oauth = form.watch('auth.oauth') ?? {}; return <Card><SectionHeader title="OAuth providers" description="Provider callbacks are derived and read-only. Configure client credentials per provider." /><CardContent className="grid gap-4 md:grid-cols-2">{OAUTH_PROVIDERS.map((provider) => { const item = oauth[provider] ?? { enabled: false, clientId: '', secretSet: false, secret: { action: '' }, fields: {} }; const special = specialFields[provider]; return <Card key={provider} size="sm"><CardHeader><div className="flex items-center justify-between"><CardTitle className="capitalize">{provider.replace('_', ' ')}</CardTitle><Toggle label="Enabled" checked={item.enabled} onChange={(next) => form.setValue(`auth.oauth.${provider}` as any, { ...item, enabled: next, fields: item.fields ?? {}, secret: item.secret ?? { action: '' } }, { shouldDirty: true })} /></div></CardHeader><CardContent className="space-y-3"><TextField form={form} name={`auth.oauth.${provider}.clientId`} label="Client ID" /><SecretEditor label="Client secret" secret={item.secret} configured={item.secretSet} onChange={(value) => form.setValue(`auth.oauth.${provider}.secret` as any, value, { shouldDirty: true })} />{special && <TextField form={form} name={`auth.oauth.${provider}.fields.${special}`} label={special} />}<Field><FieldLabel>Callback URL</FieldLabel><div className="flex gap-2"><Input value={`${form.watch('general.siteUrl').replace(/\/$/, '')}/auth/v1/callback?provider=${provider}`} readOnly /><Button type="button" size="icon" variant="outline" onClick={() => void navigator.clipboard?.writeText(`${form.watch('general.siteUrl').replace(/\/$/, '')}/auth/v1/callback?provider=${provider}`)} aria-label={`Copy ${provider} callback`}><Copy /></Button></div></Field></CardContent></Card> })}</CardContent></Card> }
function StorageSection({ form }: { form: UseFormReturn<RedactedProjectConfiguration> }) { const storage = form.watch('storage'); const object = storage.backend !== 'local'; return <Card><SectionHeader title="Storage" description="Backend selection and S3-compatible protocol are independent controls." /><CardContent className="space-y-5"><Toggle label="Enable Storage" checked={form.watch('services.storage')} onChange={(next) => { form.setValue('services.storage', next, { shouldDirty: true }); if (next) { form.setValue('services.database', true, { shouldDirty: true }); form.setValue('services.rest', true, { shouldDirty: true }); form.setValue('services.gateway', true, { shouldDirty: true }) } }} /><Field><FieldLabel>Backend</FieldLabel><Select value={storage.backend} onValueChange={(value) => { const backend = value as typeof storage.backend; form.setValue('storage.backend', backend, { shouldDirty: true }); if (backend === 'local') { for (const key of ['bucket', 'region', 'endpoint', 'accountId', 'accessKeyId'] as const) form.setValue(`storage.${key}`, '' as never, { shouldDirty: true }); form.setValue('storage.secretAccessKey', { action: '' }, { shouldDirty: true }) } }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="local">Local filesystem</SelectItem><SelectItem value="s3">Generic S3</SelectItem><SelectItem value="aws-s3">AWS S3</SelectItem><SelectItem value="r2">Cloudflare R2</SelectItem></SelectContent></Select></Field><Toggle label="Enable S3-compatible API" checked={storage.s3CompatibleApi} onChange={(next) => form.setValue('storage.s3CompatibleApi', next, { shouldDirty: true })} /><FieldGroup className="grid gap-4 md:grid-cols-2">{object && <><TextField form={form} name="storage.bucket" label="Bucket" /><TextField form={form} name="storage.region" label="Region" /><TextField form={form} name="storage.endpoint" label="Endpoint" /><TextField form={form} name="storage.accountId" label="Account ID (R2)" /><TextField form={form} name="storage.accessKeyId" label="Access key ID" /><SecretEditor label="Secret access key" secret={storage.secretAccessKey} configured={storage.secretAccessKeySet} onChange={(value) => form.setValue('storage.secretAccessKey', value, { shouldDirty: true })} /><Toggle label="Force path style" checked={storage.forcePathStyle} onChange={(next) => form.setValue('storage.forcePathStyle', next, { shouldDirty: true })} /></>}{!object && <Field><FieldLabel>Managed local path</FieldLabel><Input value={storage.localPath || 'Project-scoped runtime path'} readOnly /></Field>}</FieldGroup><Collapsible><CollapsibleTrigger className="text-sm font-medium">Advanced storage settings</CollapsibleTrigger><CollapsibleContent className="pt-4"><FieldDescription>Credentials are never persisted in the browser or returned in this form.</FieldDescription></CollapsibleContent></Collapsible></CardContent></Card> }
function RealtimeSection({ form }: { form: UseFormReturn<RedactedProjectConfiguration> }) { const enabled = form.watch('services.realtime'); return <Card><SectionHeader title="Realtime" description="Realtime is optional and only receives supported typed settings." /><CardContent className="space-y-4"><Toggle label="Enable Realtime" checked={enabled} onChange={(next) => form.setValue('services.realtime', next, { shouldDirty: true })} /><FieldGroup className="grid gap-4 md:grid-cols-2"><NumberField form={form} name="realtime.maxConnections" label="Maximum connections" /><NumberField form={form} name="realtime.databasePoolSize" label="Database pool size" /><Field><FieldLabel>Log level</FieldLabel><Select value={form.watch('realtime.logLevel')} onValueChange={(value) => form.setValue('realtime.logLevel', value as never, { shouldDirty: true })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['debug', 'info', 'warn', 'error'].map((level) => <SelectItem key={level} value={level}>{level}</SelectItem>)}</SelectContent></Select></Field></FieldGroup></CardContent></Card> }
function FunctionsSection({ form }: { form: UseFormReturn<RedactedProjectConfiguration> }) { const functions = form.watch('functions'); return <Card><SectionHeader title="Functions" description="Environment values are encrypted and rendered into the Functions runtime only." /><CardContent className="space-y-5"><Toggle label="Enable Edge Functions" checked={form.watch('services.functions')} onChange={(next) => form.setValue('services.functions', next, { shouldDirty: true })} /><Toggle label="Default JWT verification" checked={functions.defaultJwtVerification} onChange={(next) => form.setValue('functions.defaultJwtVerification', next, { shouldDirty: true })} /><Field><FieldLabel>Functions directory</FieldLabel><Input value={functions.directory} readOnly /></Field><div className="space-y-3"><div className="flex items-center justify-between"><strong className="text-sm">Environment variables</strong><Button type="button" size="sm" variant="outline" onClick={() => form.setValue('functions.variables', [...(functions.variables ?? []), { name: '', valueSet: false, value: { action: '' } }], { shouldDirty: true })}><Plus />Add variable</Button></div>{(functions.variables ?? []).map((item, index) => <div className="flex items-end gap-2" key={`${index}-${item.name}`}><TextField form={form} name={`functions.variables.${index}.name`} label="Name" /><SecretEditor label="Value" secret={item.value} configured={item.valueSet} onChange={(value) => form.setValue(`functions.variables.${index}.value` as any, value, { shouldDirty: true })} /><Button type="button" size="icon" variant="ghost" onClick={() => form.setValue('functions.variables', functions.variables?.filter((_, i) => i !== index), { shouldDirty: true })} aria-label={`Remove variable ${index + 1}`}><Trash2 /></Button></div>)}</div></CardContent></Card> }
function DatabaseSection({ projectId, form }: { projectId: string; form: UseFormReturn<RedactedProjectConfiguration> }) { const db = form.watch('database'); return <Card><SectionHeader title="Database" description="Database version and runtime limits. Password rotation is a separate sensitive operation." /><CardContent className="space-y-5"><FieldGroup className="grid gap-4 md:grid-cols-2"><Field><FieldLabel>Postgres version</FieldLabel><Input value={db.version} readOnly /></Field><Toggle label="Direct PostgreSQL port" checked={db.directPort} onChange={(next) => { form.setValue('database.directPort', next, { shouldDirty: true }); form.setValue('services.directDb', next, { shouldDirty: true }) }} /><NumberField form={form} name="database.maxConnections" label="Maximum connections" /><TextField form={form} name="database.sharedBuffers" label="Shared buffers" /></FieldGroup><Field><FieldLabel>Supported extensions</FieldLabel><Input value={db.extensions?.join(', ') ?? ''} onChange={(event) => form.setValue('database.extensions', event.target.value.split(',').map((v) => v.trim()).filter(Boolean), { shouldDirty: true })} placeholder="No extensions configured" /></Field><Alert>Direct database host ports are allocated by Manager and are read-only.</Alert><RotateDatabaseButton projectId={projectId} /></CardContent></Card> }
function PoolerSection({ form }: { form: UseFormReturn<RedactedProjectConfiguration> }) { const pooler = form.watch('pooler'); return <Card><SectionHeader title="Connection Pooler" description="Supavisor ports are allocated by Manager and retained across restarts." /><CardContent className="space-y-5"><Toggle label="Enable Supavisor" checked={form.watch('services.supavisor')} onChange={(next) => form.setValue('services.supavisor', next, { shouldDirty: true })} /><FieldGroup className="grid gap-4 md:grid-cols-2"><ReadOnlyField label="Transaction port (Manager allocated)" value={String(pooler.transactionPort || 'Pending allocation')} /><ReadOnlyField label="Session port (Manager allocated)" value={String(pooler.sessionPort || 'Pending allocation')} /><NumberField form={form} name="pooler.poolSize" label="Pool size" /><NumberField form={form} name="pooler.maxClientConnections" label="Maximum client connections" /></FieldGroup></CardContent></Card> }
function NetworkSection({ form }: { form: UseFormReturn<RedactedProjectConfiguration> }) { const network = form.watch('network'); return <Card><SectionHeader title="Gateway & Network" description="Allocated ports are read-only. HTTPS uses supported typed modes." /><CardContent className="space-y-5"><FieldGroup className="grid gap-4 md:grid-cols-2"><Field><FieldLabel>Gateway</FieldLabel><Select value={network.gateway} onValueChange={(value) => form.setValue('network.gateway', value as never, { shouldDirty: true })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="envoy">Envoy (recommended)</SelectItem><SelectItem value="kong">Kong (advanced)</SelectItem></SelectContent></Select></Field><Field><FieldLabel>HTTPS mode</FieldLabel><Select value={network.httpsMode} onValueChange={(value) => form.setValue('network.httpsMode', value as never, { shouldDirty: true })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="external">External reverse proxy</SelectItem><SelectItem value="caddy">Caddy managed</SelectItem><SelectItem value="manual" disabled>Manual certificate (unsupported)</SelectItem></SelectContent></Select></Field></FieldGroup><FieldGroup className="grid gap-4 md:grid-cols-2"><ReadOnlyField label="API port" value={String(network.apiPort || 'Manager allocated')} /><ReadOnlyField label="Studio port" value={String(network.studioPort || 'Manager allocated')} /><ReadOnlyField label="Direct database port" value={String(network.directDatabasePort || 'Disabled')} /><ReadOnlyField label="Pooler port" value={String(network.poolerPort || 'Manager allocated')} /></FieldGroup><Collapsible><CollapsibleTrigger className="text-sm font-medium">Advanced network settings</CollapsibleTrigger><CollapsibleContent className="pt-4"><ReadOnlyField label="Internal gateway port" value={String(network.internalGatewayPort || 8000)} /></CollapsibleContent></Collapsible></CardContent></Card> }
function SecretsSection({ projectId }: { projectId: string }) { const [show, setShow] = useState(false); const [values, setValues] = useState<Record<string, string>>({}); return <Card><SectionHeader title="API & Secrets" description="Project URL and Anon Key are safe project outputs. Sensitive values require recent administrator authentication." /><CardContent className="space-y-5"><ReadOnlyField label="Project URL" value="Derived from General → Domain" /><ReadOnlyField label="Anon Key" value="Available to client applications (redacted by server projection)" /><RevealActions onReveal={() => setShow(true)} /><RevealDialog projectId={projectId} show={show} values={values} onClose={() => setShow(false)} onRevealed={(kind, value) => { setValues((current) => ({ ...current, [kind]: value })); window.setTimeout(() => setValues((current) => { const next = { ...current }; delete next[kind]; return next }), 60_000) }} /></CardContent></Card> }
function RevealActions({ onReveal }: { onReveal: () => void }) { return <div className="rounded-lg border border-border p-4"><div className="flex items-center gap-2"><AlertTriangle className="size-4 text-amber-400" /><strong className="text-sm">Sensitive values</strong></div><p className="mt-2 text-sm text-muted-foreground">Reveal requires the administrator password. Plaintext is kept in component memory only and cleared automatically.</p><div className="mt-3 flex flex-wrap gap-2"><Button type="button" variant="outline" size="sm" onClick={onReveal}><Eye className="size-4" />Reveal secrets</Button></div></div> }
function RotateDatabaseButton({ projectId }: { projectId: string }) { const [open, setOpen] = useState(false); const [password, setPassword] = useState(''); const queryClient = useQueryClient(); const rotate = useMutation({ mutationFn: () => apiFetch<{ operationId: string }>(`/api/projects/${projectId}/secrets/databasePassword/rotate`, { method: 'POST', body: JSON.stringify({ password }) }), onSuccess: () => { setOpen(false); setPassword(''); void queryClient.invalidateQueries({ queryKey: ['project-configuration', projectId] }); toast.success('Database password rotation queued') } }); return <><Button type="button" variant="destructive" onClick={() => setOpen(true)}><RotateCw className="size-4" />Rotate database password</Button><AlertDialog open={open} onOpenChange={setOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Rotate database password?</AlertDialogTitle><AlertDialogDescription>This is a separate sensitive operation. Existing database clients will need the new password after runtime reconciliation.</AlertDialogDescription></AlertDialogHeader><Input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Administrator password" autoComplete="current-password" /><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={!password || rotate.isPending} onClick={() => rotate.mutate()}>Confirm rotation</AlertDialogAction></AlertDialogFooter>{rotate.error && <Alert variant="destructive">{rotate.error.message}</Alert>}</AlertDialogContent></AlertDialog></> }
function RevealDialog({ projectId, show, values, onClose, onRevealed }: { projectId: string; show: boolean; values: Record<string, string>; onClose: () => void; onRevealed: (kind: string, value: string) => void }) { const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const kinds = ['serviceRoleKey', 'jwtSecret', 'databasePassword', 'anonKey']; useEffect(() => { const handler = () => setPassword(''); document.addEventListener('configuration:reveal', handler); return () => document.removeEventListener('configuration:reveal', handler) }, []); return <AlertDialog open={show} onOpenChange={(open) => !open && onClose()}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reveal sensitive secrets</AlertDialogTitle><AlertDialogDescription>Confirm your administrator password. Values are never written to URL or browser storage.</AlertDialogDescription></AlertDialogHeader><Input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Administrator password" autoComplete="current-password" />{kinds.map((kind) => <div className="flex items-center justify-between gap-2" key={kind}><span className="text-sm">{kind}</span>{values[kind] ? <code className="max-w-[220px] truncate">{values[kind]}</code> : <Button type="button" size="sm" variant="outline" disabled={busy} onClick={async () => { setBusy(true); try { const result = await apiFetch<{ value: string }>(`/api/projects/${projectId}/secrets/${kind}/reveal`, { method: 'POST', body: JSON.stringify({ password }) }); onRevealed(kind, result.value) } finally { setBusy(false) } }}>Reveal</Button>}</div>)}<AlertDialogFooter><AlertDialogCancel onClick={() => setPassword('')}>Close</AlertDialogCancel></AlertDialogFooter></AlertDialogContent></AlertDialog> }

function SectionHeader({ title, description }: { title: string; description: string }) { return <CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader> }
function Toggle({ label, checked, onChange, disabled, description }: { label: string; checked: boolean; onChange: (value: boolean) => void; disabled?: boolean; description?: string }) { return <Field className="rounded-lg border border-border p-3"><div className="flex items-center justify-between gap-3"><FieldLabel>{label}</FieldLabel><Switch checked={checked} onCheckedChange={onChange} disabled={disabled} /></div>{description && <FieldDescription>{description}</FieldDescription>}</Field> }
function TextField({ form, name, label }: { form: UseFormReturn<RedactedProjectConfiguration>; name: string; label: string }) { const error = fieldError(form, name); return <Field><FieldLabel htmlFor={name}>{label}</FieldLabel><Input id={name} {...form.register(name as never)} aria-invalid={!!error} /><FieldError>{error}</FieldError></Field> }
function NumberField({ form, name, label }: { form: UseFormReturn<RedactedProjectConfiguration>; name: string; label: string }) { const error = fieldError(form, name); return <Field><FieldLabel htmlFor={name}>{label}</FieldLabel><Input id={name} type="number" {...form.register(name as never, { valueAsNumber: true })} aria-invalid={!!error} /><FieldError>{error}</FieldError></Field> }
function ReadOnlyField({ label, value }: { label: string; value: string }) { return <Field><FieldLabel>{label}</FieldLabel><Input value={value} readOnly /></Field> }
function SecretEditor({ label, secret, configured, onChange }: { label: string; secret: any; configured: boolean; onChange: (value: any) => void }) { const [visible, setVisible] = useState(false); const [value, setValue] = useState(''); useEffect(() => () => setValue(''), []); return <Field><div className="flex items-center justify-between"><FieldLabel>{label}</FieldLabel>{configured && <Badge variant="outline">Configured</Badge>}</div><div className="flex gap-2"><Input type={visible ? 'text' : 'password'} value={value} placeholder={configured ? 'Configured — enter to replace' : 'Enter a secret'} onChange={(event) => { const next = event.target.value; setValue(next); onChange(next ? { action: 'replace', value: next } : { action: '' }) }} /><Button type="button" variant="outline" size="icon" onClick={() => setVisible((current) => !current)} aria-label={visible ? `Hide ${label}` : `Show ${label}`}>{visible ? <EyeOff /> : <Eye />}</Button></div>{configured && <div className="flex gap-2"><Button type="button" size="sm" variant="ghost" onClick={() => onChange({ action: 'retain' })}>Retain</Button><Button type="button" size="sm" variant="ghost" onClick={() => onChange({ action: 'remove' })}>Remove</Button></div>}<FieldDescription>Plaintext is held in memory only.</FieldDescription></Field> }
function fieldError(form: UseFormReturn<RedactedProjectConfiguration>, name: string) { let value: any = form.formState.errors; for (const part of name.split('.')) value = value?.[part]; return (value?.message || value?.value?.message) as string | undefined }
function serviceName(name: string) { return ({ postgresMeta: 'postgres-meta', directDb: 'Direct PostgreSQL port', imgproxy: 'Image Transformation', supavisor: 'Supavisor', rest: 'PostgREST' } as Record<string, string>)[name] ?? name.charAt(0).toUpperCase() + name.slice(1) }
const configurationUpdateSchema = z.object({}).passthrough()
