import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation } from '@tanstack/react-query'
import { Database, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { Alert } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Field, FieldDescription, FieldError, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { CopyButton } from '@/components/app/CopyButton'
import { apiFetch } from '../../api/client'
const schema = z.object({ username: z.string().min(3).max(64).regex(/^[A-Za-z0-9][A-Za-z0-9._-]+$/), password: z.string().min(12, 'Password must contain at least 12 characters'), confirmPassword: z.string() }).refine((value) => value.password === value.confirmPassword, { message: 'Passwords do not match', path: ['confirmPassword'] })
type SetupForm = z.infer<typeof schema>
export function SetupPage() {
  const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]); const form = useForm<SetupForm>({ resolver: zodResolver(schema), defaultValues: { username: '', password: '', confirmPassword: '' } }); const setup = useMutation({ mutationFn: (values: SetupForm) => apiFetch<{ recoveryCodes: string[] }>('/api/setup', { method: 'POST', body: JSON.stringify({ username: values.username, password: values.password }) }), onSuccess: (result) => setRecoveryCodes(result.recoveryCodes) })
  if (recoveryCodes.length > 0) return <main className="auth-layout"><Card className="w-full max-w-md"><CardHeader><span className="mb-3 inline-flex size-10 items-center justify-center rounded-lg border border-primary/25 bg-primary/10 text-primary"><ShieldCheck className="size-5" /></span><p className="eyebrow">Account recovery</p><h1 className="text-base font-medium">Save your recovery codes</h1><CardDescription>These codes are shown once. Store them somewhere private before continuing.</CardDescription></CardHeader><CardContent><ul className="grid grid-cols-2 gap-2 p-0" aria-label="Recovery codes">{recoveryCodes.map((code) => <li className="rounded-md border bg-muted p-2 text-center" key={code}><code>{code}</code></li>)}</ul><div className="mt-5 flex justify-end"><CopyButton value={recoveryCodes.join('\n')} label="Recovery codes" /></div><Button className="mt-3 w-full" nativeButton={false} render={<a href="/login" />}>Continue to sign in</Button></CardContent></Card></main>
  return <main className="auth-layout"><Card data-testid="setup-card" className="w-full max-w-md"><CardHeader><div className="mb-4 flex items-center gap-2 font-semibold"><span className="inline-flex size-9 items-center justify-center rounded-lg border border-primary/25 bg-primary/10 text-primary"><Database className="size-5" /></span>Supabase Manager</div><p className="eyebrow">First-time setup</p><CardTitle>Create the administrator</CardTitle><CardDescription>This account controls every Supabase runtime on this server.</CardDescription></CardHeader><CardContent><form onSubmit={form.handleSubmit((values) => setup.mutate(values))} className="space-y-4"><Field data-invalid={Boolean(form.formState.errors.username)}><FieldLabel htmlFor="setup-username">Username</FieldLabel><Input id="setup-username" autoComplete="username" aria-invalid={Boolean(form.formState.errors.username)} aria-describedby={`setup-username-description${form.formState.errors.username ? ' setup-username-error' : ''}`} {...form.register('username')} /><FieldDescription id="setup-username-description">Use a unique administrator username for this Manager.</FieldDescription>{form.formState.errors.username && <FieldError id="setup-username-error">{form.formState.errors.username.message}</FieldError>}</Field><Field data-invalid={Boolean(form.formState.errors.password)}><FieldLabel htmlFor="setup-password">Password</FieldLabel><Input id="setup-password" type="password" autoComplete="new-password" minLength={12} aria-describedby={`password-hint${form.formState.errors.password ? ' setup-password-error' : ''}`} aria-invalid={Boolean(form.formState.errors.password)} {...form.register('password')} /><FieldDescription id="password-hint">Use 12 or more characters.</FieldDescription>{form.formState.errors.password && <FieldError id="setup-password-error">{form.formState.errors.password.message}</FieldError>}</Field><Field data-invalid={Boolean(form.formState.errors.confirmPassword)}><FieldLabel htmlFor="setup-confirm-password">Confirm password</FieldLabel><Input id="setup-confirm-password" type="password" autoComplete="new-password" aria-invalid={Boolean(form.formState.errors.confirmPassword)} aria-describedby={`setup-confirm-description${form.formState.errors.confirmPassword ? ' setup-confirm-error' : ''}`} {...form.register('confirmPassword')} /><FieldDescription id="setup-confirm-description">Repeat the administrator password exactly.</FieldDescription>{form.formState.errors.confirmPassword && <FieldError id="setup-confirm-error">{form.formState.errors.confirmPassword.message}</FieldError>}</Field>{setup.error && <Alert variant="destructive">{setup.error.message}</Alert>}<Button className="w-full" disabled={setup.isPending} type="submit">{setup.isPending ? 'Creating…' : 'Create administrator'}</Button></form></CardContent></Card></main>
}
