import type { UseFormReturn } from 'react-hook-form'
import { useEffect } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Switch } from '@/components/ui/switch'
import { Textarea } from '@/components/ui/textarea'
import type { ProjectForm } from './projectSchema'
import { OAuthProviderFields } from './OAuthProviderFields'
import { setServiceEnabled } from './PresetStep'

export function AuthStep({ form }: { form: UseFormReturn<ProjectForm> }) {
  const auth = form.watch('configuration.auth'); const smtp = auth.smtp; const error = (name: string) => { let value: any = form.formState.errors; for (const part of name.split('.')) value = value?.[part]; return value?.message as string | undefined }
  useEffect(() => { const allowed = auth.phone.provider === 'twilio' ? ['accountSid', 'messageServiceSid', 'verifySid'] : auth.phone.provider === 'messagebird' ? ['originator'] : auth.phone.provider === 'textlocal' ? ['sender'] : []; const fields = Object.fromEntries(Object.entries(auth.phone.fields).filter(([key]) => allowed.includes(key))); if (Object.keys(fields).length !== Object.keys(auth.phone.fields).length) form.setValue('configuration.auth.phone.fields', fields, { shouldDirty: true }) }, [auth.phone.provider, form])
  const set = (name: string, value: unknown) => { form.setValue(name as any, value as any, { shouldDirty: true, shouldValidate: true }); form.setValue('preset', 'CUSTOM', { shouldDirty: true }) }
  const toggleSignup = (allow: boolean) => { set('configuration.auth.email.allowSignup', allow); set('configuration.auth.disableSignup', !allow) }
  return <Card><CardHeader><CardTitle>Authentication, SMTP & OAuth</CardTitle><CardDescription>Auth policy, email delivery, phone providers, redirects and all supported OAuth providers.</CardDescription></CardHeader><CardContent className="space-y-8">
    <FieldGroup className="grid gap-4 md:grid-cols-2"><Toggle label="Auth service" checked={auth.enabled} onChange={(value) => setServiceEnabled(form, 'auth', value)} /><Toggle label="Email Auth" checked={auth.email.enabled} onChange={(value) => set('configuration.auth.email.enabled', value)} /><Toggle label="Allow signup" checked={auth.email.allowSignup} onChange={toggleSignup} /><Toggle label="Confirm email" checked={auth.email.confirmEmail} onChange={(value) => set('configuration.auth.email.confirmEmail', value)} /><Toggle label="Secure email change" checked={auth.email.secureEmailChange} onChange={(value) => { set('configuration.auth.email.secureEmailChange', value); set('configuration.auth.email.doubleConfirmChanges', value) }} /><Toggle label="Double confirm changes" checked={auth.email.doubleConfirmChanges} onChange={(value) => { set('configuration.auth.email.doubleConfirmChanges', value); set('configuration.auth.email.secureEmailChange', value) }} /><Toggle label="Anonymous sign-in" checked={auth.anonymousSignIn} onChange={(value) => set('configuration.auth.anonymousSignIn', value)} /><Field><FieldLabel htmlFor="jwt-expiry">Session JWT expiry (seconds)</FieldLabel><Input id="jwt-expiry" type="number" {...form.register('configuration.auth.jwtExpiry', { valueAsNumber: true })} aria-invalid={!!error('configuration.auth.jwtExpiry')} /><FieldError>{error('configuration.auth.jwtExpiry')}</FieldError></Field></FieldGroup>
    <Field><FieldLabel htmlFor="redirect-urls">Redirect URLs</FieldLabel><FieldDescription>One absolute http(s) URL per line.</FieldDescription><Textarea id="redirect-urls" value={auth.redirectUrls.join('\n')} onChange={(event) => set('configuration.auth.redirectUrls', event.target.value.split(/\n/).map((value) => value.trim()).filter(Boolean))} aria-invalid={!!error('configuration.auth.redirectUrls')} /><FieldError>{error('configuration.auth.redirectUrls')}</FieldError></Field>
    <section className="space-y-4"><h3 className="font-medium">Phone Auth</h3><Toggle label="Enable Phone Auth" checked={auth.phone.enabled} onChange={(value) => set('configuration.auth.phone.enabled', value)} /><Field><FieldLabel>Provider</FieldLabel><Select value={auth.phone.provider || undefined} onValueChange={(value) => set('configuration.auth.phone.provider', value)}><SelectTrigger aria-label="Phone provider"><SelectValue placeholder="Choose provider" /></SelectTrigger><SelectContent><SelectItem value="twilio">Twilio</SelectItem><SelectItem value="messagebird">MessageBird</SelectItem><SelectItem value="textlocal">Textlocal</SelectItem></SelectContent></Select><FieldError>{error('configuration.auth.phone.provider')}</FieldError></Field>{auth.phone.enabled && <><FieldGroup className="grid gap-4 md:grid-cols-2">{auth.phone.provider === 'twilio' && <><TextField label="Account SID" name="configuration.auth.phone.fields.accountSid" form={form} /><TextField label="Message Service SID" name="configuration.auth.phone.fields.messageServiceSid" form={form} /></>}{auth.phone.provider === 'messagebird' && <TextField label="Originator" name="configuration.auth.phone.fields.originator" form={form} />}{auth.phone.provider === 'textlocal' && <TextField label="Sender" name="configuration.auth.phone.fields.sender" form={form} />}<SecretField label="Provider secret" path="configuration.auth.phone.secret" set={set} configured={auth.phone.secretSet} error={error('configuration.auth.phone.secret')} /></FieldGroup></>}</section>
    <section className="space-y-4"><h3 className="font-medium">Custom SMTP</h3><Toggle label="Enable custom SMTP" checked={smtp.enabled} onChange={(value) => set('configuration.auth.smtp.enabled', value)} />{smtp.enabled && <FieldGroup className="grid gap-4 md:grid-cols-2"><TextField label="Host" name="configuration.auth.smtp.host" form={form} /><NumberField label="Port" name="configuration.auth.smtp.port" form={form} /><TextField label="Username" name="configuration.auth.smtp.username" form={form} /><SecretField label="Password" path="configuration.auth.smtp.password" set={set} configured={smtp.passwordSet} error={error('configuration.auth.smtp.password')} /><TextField label="Sender email" name="configuration.auth.smtp.senderEmail" form={form} /><TextField label="Sender name" name="configuration.auth.smtp.senderName" form={form} /></FieldGroup>}</section>
    <section className="space-y-4"><h3 className="font-medium">OAuth providers</h3><OAuthProviderFields form={form} siteUrl={form.watch('configuration.general.siteUrl')} /></section>
  </CardContent></Card>
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { const id = `toggle-${label.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`; return <Field orientation="horizontal" className="items-center justify-between rounded-lg border border-border px-3 py-2"><FieldLabel htmlFor={id}>{label}</FieldLabel><Switch id={id} checked={checked} onCheckedChange={onChange} /></Field> }
function TextField({ label, name, form }: { label: string; name: string; form: UseFormReturn<ProjectForm> }) { return <Field><FieldLabel htmlFor={name}>{label}</FieldLabel><Input id={name} {...form.register(name as any)} /></Field> }
function NumberField({ label, name, form }: { label: string; name: string; form: UseFormReturn<ProjectForm> }) { return <Field><FieldLabel htmlFor={name}>{label}</FieldLabel><Input id={name} type="number" {...form.register(name as any, { valueAsNumber: true })} /></Field> }
function SecretField({ label, path, set, configured, error }: { label: string; path: string; set: (name: string, value: unknown) => void; configured: boolean; error?: string }) { return <Field><FieldLabel htmlFor={path}>{label}</FieldLabel><Input id={path} type="password" placeholder={configured ? 'Configured — enter to replace' : ''} onChange={(event) => set(path, event.target.value ? { action: 'replace', value: event.target.value } : { action: 'retain' })} aria-invalid={!!error} /><FieldError>{error}</FieldError></Field> }
