import type { UseFormReturn } from 'react-hook-form'
import type { ProjectForm } from './projectSchema'
import { OAuthProviderFields } from './OAuthProviderFields'

export function AuthStep({ form }: { form: UseFormReturn<ProjectForm> }) {
  const auth=form.watch('configuration.auth'); const smtp=auth.smtp
  const set=(name:string,value:unknown)=>form.setValue(name as any,value as any,{shouldDirty:true,shouldValidate:true})
  return <section className="wizard-section"><div className="section-heading"><span>03</span><div><h2>Authentication, SMTP & OAuth</h2><p>Typed settings and generated callback URLs keep Auth safe.</p></div></div><div className="form-grid"><label><span>Auth enabled</span><input type="checkbox" checked={auth.enabled} onChange={e=>set('configuration.auth.enabled',e.target.checked)} /></label><label><span>Email Auth enabled</span><input type="checkbox" checked={auth.email.enabled} onChange={e=>set('configuration.auth.email.enabled',e.target.checked)} /></label><label><span>Allow signup</span><input type="checkbox" checked={auth.email.allowSignup} onChange={e=>{set('configuration.auth.email.allowSignup',e.target.checked);set('configuration.auth.disableSignup',!e.target.checked)}} /></label><label><span>Confirm email</span><input type="checkbox" checked={auth.email.confirmEmail} onChange={e=>set('configuration.auth.email.confirmEmail',e.target.checked)} /></label><label><span>Anonymous sign-in</span><input type="checkbox" checked={auth.anonymousSignIn} onChange={e=>set('configuration.auth.anonymousSignIn',e.target.checked)} /></label><label>JWT expiry (seconds)<input type="number" {...form.register('configuration.auth.jwtExpiry',{valueAsNumber:true})} /></label></div><label>Redirect URLs (one per line)<textarea value={auth.redirectUrls.join('\n')} onChange={e=>set('configuration.auth.redirectUrls',e.target.value.split(/\n/).map(v=>v.trim()).filter(Boolean))} /></label><div className="subsection"><h3>Custom SMTP</h3><label><input type="checkbox" checked={smtp.enabled} onChange={e=>set('configuration.auth.smtp.enabled',e.target.checked)} /> Enable custom SMTP</label>{smtp.enabled&&<div className="form-grid"><label>Host<input {...form.register('configuration.auth.smtp.host')} /></label><label>Port<input type="number" {...form.register('configuration.auth.smtp.port',{valueAsNumber:true})} /></label><label>Username<input {...form.register('configuration.auth.smtp.username')} /></label><label>Password<input type="password" placeholder={smtp.passwordSet?'Configured — enter to replace':''} onChange={e=>set('configuration.auth.smtp.password',e.target.value?{action:'replace',value:e.target.value}:{action:'retain'})} /></label><label>Sender email<input {...form.register('configuration.auth.smtp.senderEmail')} /></label><label>Sender name<input {...form.register('configuration.auth.smtp.senderName')} /></label></div>}</div><div className="subsection"><h3>OAuth providers</h3><OAuthProviderFields form={form} siteUrl={form.getValues('configuration.general.siteUrl')} /></div></section>
}
