import { useQuery } from '@tanstack/react-query'
import { ArrowRight, Box, Cpu, Database, HardDrive, MemoryStick, Plus } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Badge } from '@/components/ui/badge'
import { Alert } from '@/components/ui/alert'
import { buttonVariants } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { apiFetch } from '../../api/client'
import type { HostResources, Project } from '../../api/types'
export function ProjectsPage() {
  const query = useQuery({ queryKey: ['projects'], queryFn: () => apiFetch<{ projects: Project[] }>('/api/projects') })
  const resources = useQuery({ queryKey: ['host-resources'], queryFn: () => apiFetch<HostResources>('/api/host/resources'), staleTime: 30_000, retry: false })
  const host = resources.data
  const projects = query.data?.projects ?? []
  return <main className="page"><div className="page-heading"><div><p className="eyebrow">Runtime orchestration</p><h1>Projects</h1><p className="muted">Independent official Supabase stacks on this server.</p></div><Link className={buttonVariants()} to="/projects/new"><Plus className="size-4" /> New project</Link></div><section className="host-grid" aria-label="Host resources"><Metric icon={<Cpu />} label="CPU" value={host ? `${Math.round(host.cpuPercent)}%` : '—'} detail={host ? `${host.cpuCores} cores` : 'Live metrics unavailable'} /><Metric icon={<MemoryStick />} label="Memory" value={host ? `${formatBytes(host.memoryUsedBytes)} / ${formatBytes(host.memoryTotalBytes)}` : '—'} detail={host ? `${usagePercent(host.memoryUsedBytes, host.memoryTotalBytes)}% used` : 'Available memory'} /><Metric icon={<HardDrive />} label="Disk" value={host ? `${formatBytes(host.diskUsedBytes)} / ${formatBytes(host.diskTotalBytes)}` : '—'} detail={host ? `${usagePercent(host.diskUsedBytes, host.diskTotalBytes)}% used` : 'Project data volume'} /></section><Card data-testid="projects-card"><CardHeader><CardTitle>All projects</CardTitle><CardDescription>{projects.length} configured runtimes</CardDescription></CardHeader><CardContent className="p-0">{query.isLoading && <div className="empty-state">Loading projects…</div>}{query.error && <Alert variant="destructive" className="rounded-none border-x-0 border-t-0">{query.error.message}</Alert>}{!query.isLoading && !query.error && projects.length === 0 && <div className="empty-state"><Box className="size-7" /><h3>No projects yet</h3><p>Create a complete project from the guided configuration wizard.</p></div>}{projects.length > 0 && <Table><TableHeader><TableRow><TableHead>Project</TableHead><TableHead>Health</TableHead><TableHead>Version</TableHead><TableHead className="text-right">Open</TableHead></TableRow></TableHeader><TableBody>{projects.map((project) => <TableRow key={project.id}><TableCell><Link className="flex items-center gap-3" to={`/projects/${project.id}/overview`}><span className="inline-flex size-8 items-center justify-center rounded-md border text-primary"><Database className="size-4" /></span><span><strong className="block">{project.name}</strong><small className="text-muted-foreground">https://{project.domain}</small></span></Link></TableCell><TableCell><Badge variant={project.health === 'HEALTHY' ? 'default' : project.health === 'UNHEALTHY' ? 'destructive' : 'outline'}>{labelHealth(project.health)}</Badge></TableCell><TableCell className="font-mono text-xs text-muted-foreground">{project.supabaseVersion}</TableCell><TableCell className="text-right"><Link aria-label={`Open ${project.name}`} to={`/projects/${project.id}/overview`}><ArrowRight className="ml-auto size-4" /></Link></TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card></main>
}
function Metric({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string; detail: string }) { return <Card size="sm"><CardContent className="flex items-center gap-3"><span className="inline-flex size-9 items-center justify-center rounded-md bg-muted text-muted-foreground">{icon}</span><div><small className="block text-xs uppercase text-muted-foreground">{label}</small><strong className="block text-lg">{value}</strong><p className="m-0 text-xs text-muted-foreground">{detail}</p></div></CardContent></Card> }
function formatBytes(bytes: number) { if (!Number.isFinite(bytes) || bytes < 0) return '—'; const units = ['B', 'KB', 'MB', 'GB', 'TB']; let value = bytes; let unit = 0; while (value >= 1024 && unit < units.length - 1) { value /= 1024; unit += 1 } return `${unit === 0 ? Math.round(value) : value.toFixed(1)} ${units[unit]}` }
function usagePercent(used: number, total: number) { if (!Number.isFinite(used) || !Number.isFinite(total) || total <= 0) return '—'; return Math.min(100, Math.max(0, (used / total) * 100)).toFixed(0) }
function labelHealth(health: Project['health']) { return health.charAt(0) + health.slice(1).toLowerCase() }
