import { z } from 'zod'
import type { ProjectConfiguration, Preset, SecretAction, Services } from '../../api/types'

export const PRESETS = ['LIGHTWEIGHT', 'STANDARD', 'FULL', 'CUSTOM'] as const
export const SUPABASE_VERSION = 'self-hosted/v0.8.0'
export const OAUTH_PROVIDERS = ['apple', 'azure', 'bitbucket', 'discord', 'facebook', 'figma', 'github', 'gitlab', 'google', 'kakao', 'keycloak', 'linkedin_oidc', 'notion', 'slack_oidc', 'snapchat', 'spotify', 'twitch', 'twitter', 'workos', 'zoom'] as const
export type OAuthProvider = (typeof OAUTH_PROVIDERS)[number]
export type PresetName = (typeof PRESETS)[number]

const serviceKeys = ['database', 'gateway', 'auth', 'rest', 'studio', 'postgresMeta', 'realtime', 'storage', 'imgproxy', 'functions', 'supavisor', 'logs', 'vector', 'directDb'] as const
export const lightweightServices: Services = { database: true, gateway: true, auth: true, rest: true, studio: true, postgresMeta: true, realtime: false, storage: false, imgproxy: false, functions: false, supavisor: false, logs: false, vector: false, directDb: false }
const httpUrl = (message = 'Enter an http or https URL') => z.string().refine((value) => { try { const parsed = new URL(value); return (parsed.protocol === 'http:' || parsed.protocol === 'https:') && !!parsed.hostname } catch { return false } }, message)
const optionalHttpUrl = z.string().refine((value) => !value || httpUrl().safeParse(value).success, 'Enter an http or https URL')
const secretSchema = z.object({ action: z.enum(['retain', 'replace', 'remove']), value: z.string().optional() }).superRefine((secret, context) => { if (secret.action === 'replace' && !secret.value?.trim()) context.addIssue({ code: 'custom', path: ['value'], message: 'A replacement value is required' }); if (secret.action !== 'replace' && secret.value) context.addIssue({ code: 'custom', path: ['value'], message: 'Only replace accepts a value' }) })
const serviceSchema = z.object({ database: z.boolean(), gateway: z.boolean(), auth: z.boolean(), rest: z.boolean(), studio: z.boolean(), postgresMeta: z.boolean(), realtime: z.boolean(), storage: z.boolean(), imgproxy: z.boolean(), functions: z.boolean(), supavisor: z.boolean(), logs: z.boolean(), vector: z.boolean(), directDb: z.boolean() }).superRefine((services, context) => { if (!services.database) context.addIssue({ code: 'custom', path: ['database'], message: 'PostgreSQL is required' }); if (services.studio && !services.postgresMeta) context.addIssue({ code: 'custom', path: ['postgresMeta'], message: 'postgres-meta is required by Studio' }); if (services.imgproxy && !services.storage) context.addIssue({ code: 'custom', path: ['imgproxy'], message: 'Image Transformation requires Storage' }); if (services.vector !== services.logs) context.addIssue({ code: 'custom', path: ['vector'], message: 'Logs and Vector must be enabled together' }); if ((services.auth || services.rest || services.studio || services.realtime || services.storage) && !services.gateway) context.addIssue({ code: 'custom', path: ['gateway'], message: 'API Gateway is required by enabled public services' }) })
const smtpSchema = z.object({ enabled: z.boolean(), host: z.string(), port: z.number().int().min(1).max(65535), username: z.string(), passwordSet: z.boolean(), password: secretSchema, senderEmail: z.string(), senderName: z.string() }).superRefine((smtp, context) => { if (!smtp.enabled) return; for (const key of ['host', 'username', 'senderName'] as const) if (!smtp[key].trim()) context.addIssue({ code: 'custom', path: [key], message: 'Required when SMTP is enabled' }); if (!z.email().safeParse(smtp.senderEmail).success) context.addIssue({ code: 'custom', path: ['senderEmail'], message: 'Enter a valid email address' }); if (!smtp.passwordSet && smtp.password.action !== 'replace') context.addIssue({ code: 'custom', path: ['password'], message: 'Enter an SMTP password' }); if (smtp.password.action === 'remove') context.addIssue({ code: 'custom', path: ['password'], message: 'Cannot remove password while SMTP is enabled' }) })
export const specialFields: Record<string, string> = { azure: 'tenantUrl', github: 'enterpriseUrl', gitlab: 'selfHostedUrl', keycloak: 'realmUrl' }
const oauthSchema = z.object({ enabled: z.boolean(), clientId: z.string(), secretSet: z.boolean(), secret: secretSchema, fields: z.record(z.string(), z.string()) }).superRefine((oauth, context) => { if (!oauth.enabled) return; if (!oauth.clientId.trim()) context.addIssue({ code: 'custom', path: ['clientId'], message: 'Required when provider is enabled' }); if (!oauth.secretSet && oauth.secret.action !== 'replace') context.addIssue({ code: 'custom', path: ['secret'], message: 'Enter a client secret' }); if (oauth.secret.action === 'remove') context.addIssue({ code: 'custom', path: ['secret'], message: 'Cannot remove a secret while provider is enabled' }) })
const phoneSchema = z.object({ enabled: z.boolean(), provider: z.string(), secretSet: z.boolean(), secret: secretSchema, fields: z.record(z.string(), z.string()) }).superRefine((phone, context) => { if (!phone.enabled && !phone.provider && !Object.keys(phone.fields).length && !phone.secretSet && phone.secret.action === 'retain') return; if (!['twilio', 'messagebird', 'textlocal'].includes(phone.provider)) context.addIssue({ code: 'custom', path: ['provider'], message: 'Choose Twilio, MessageBird, or Textlocal' }); const required = phone.provider === 'twilio' ? ['accountSid', 'messageServiceSid'] : phone.provider === 'messagebird' ? ['originator'] : phone.provider === 'textlocal' ? ['sender'] : []; for (const field of required) if (!phone.fields[field]?.trim()) context.addIssue({ code: 'custom', path: ['fields', field], message: 'Required for this provider' }); if (phone.enabled && !phone.secretSet && phone.secret.action !== 'replace') context.addIssue({ code: 'custom', path: ['secret'], message: 'Enter a provider secret' }); if (phone.enabled && phone.secret.action === 'remove') context.addIssue({ code: 'custom', path: ['secret'], message: 'Cannot remove a secret while Phone Auth is enabled' }) })
const authSchema = z.object({ enabled: z.boolean(), jwtExpiry: z.number().int().min(0).max(31536000), disableSignup: z.boolean(), email: z.object({ enabled: z.boolean(), allowSignup: z.boolean(), confirmEmail: z.boolean(), secureEmailChange: z.boolean(), doubleConfirmChanges: z.boolean() }), phone: phoneSchema, anonymousSignIn: z.boolean(), redirectUrls: z.array(httpUrl()), oauth: z.record(z.string(), oauthSchema), smtp: smtpSchema }).superRefine((auth, context) => { if (auth.disableSignup !== !auth.email.allowSignup) context.addIssue({ code: 'custom', path: ['disableSignup'], message: 'Must match the email signup policy' }); if (auth.disableSignup && (auth.phone.enabled || auth.anonymousSignIn || Object.values(auth.oauth).some((provider) => provider.enabled))) context.addIssue({ code: 'custom', path: ['disableSignup'], message: 'Phone, anonymous, and OAuth signup require signup to be enabled' }); if (auth.email.secureEmailChange !== auth.email.doubleConfirmChanges) context.addIssue({ code: 'custom', path: ['email', 'secureEmailChange'], message: 'Must match double confirmation' }); for (const [provider, config] of Object.entries(auth.oauth)) { if (!(OAUTH_PROVIDERS as readonly string[]).includes(provider)) context.addIssue({ code: 'custom', path: ['oauth', provider], message: 'Unsupported OAuth provider' }); const special = specialFields[provider]; for (const [field, value] of Object.entries(config.fields)) { if (field !== special) context.addIssue({ code: 'custom', path: ['oauth', provider, 'fields', field], message: 'Unsupported provider field' }); else if (value && !optionalHttpUrl.safeParse(value).success) context.addIssue({ code: 'custom', path: ['oauth', provider, 'fields', field], message: 'Enter an http or https URL' }) }; if (config.enabled && special && !config.fields[special]?.trim()) context.addIssue({ code: 'custom', path: ['oauth', provider, 'fields', special], message: 'Required for this provider' }) } })
const storageSchema = z.object({ backend: z.enum(['local', 's3', 'aws-s3', 'r2']), s3CompatibleApi: z.boolean(), bucket: z.string(), region: z.string(), endpoint: z.string(), accountId: z.string(), accessKeyId: z.string(), secretAccessKeySet: z.boolean(), secretAccessKey: secretSchema, forcePathStyle: z.boolean(), localPath: z.string() }).superRefine((storage, context) => { if (storage.backend === 'local') { if (storage.bucket || storage.region || storage.endpoint || storage.accountId || storage.accessKeyId || storage.secretAccessKeySet || storage.secretAccessKey.action !== 'retain' || storage.forcePathStyle) context.addIssue({ code: 'custom', path: ['backend'], message: 'Local storage cannot include object-storage settings' }); return }; for (const key of ['bucket', 'accessKeyId'] as const) if (!storage[key].trim()) context.addIssue({ code: 'custom', path: [key], message: 'Required for object storage' }); if (storage.backend !== 'r2' && !storage.region.trim()) context.addIssue({ code: 'custom', path: ['region'], message: 'Region is required' }); if (!storage.secretAccessKeySet && storage.secretAccessKey.action !== 'replace') context.addIssue({ code: 'custom', path: ['secretAccessKey'], message: 'Enter a secret access key' }); if (storage.secretAccessKey.action === 'remove') context.addIssue({ code: 'custom', path: ['secretAccessKey'], message: 'Cannot remove an object-storage secret' }); if (storage.backend === 's3' && !storage.endpoint.trim()) context.addIssue({ code: 'custom', path: ['endpoint'], message: 'Endpoint is required for generic S3' }); if (storage.backend === 'r2' && !storage.accountId.trim()) context.addIssue({ code: 'custom', path: ['accountId'], message: 'Account ID is required for Cloudflare R2' }); if (storage.backend === 'r2' && storage.endpoint) context.addIssue({ code: 'custom', path: ['endpoint'], message: 'R2 endpoint is derived from account ID' }); if (storage.endpoint && !httpUrl().safeParse(storage.endpoint).success) context.addIssue({ code: 'custom', path: ['endpoint'], message: 'Enter an http or https URL' }) })
const envName = /^[A-Z_][A-Z0-9_]*$/
const reservedEnv = new Set(['ANON_KEY', 'SERVICE_ROLE_KEY', 'JWT_SECRET', 'SUPABASE_URL', 'SUPABASE_PUBLIC_URL', 'FUNCTIONS_VERIFY_JWT', 'POSTGRES_PASSWORD'])
const functionsSchema = z.object({ defaultJwtVerification: z.boolean(), directory: z.string(), variables: z.array(z.object({ name: z.string(), valueSet: z.boolean(), value: secretSchema })) }).superRefine((functions, context) => functions.variables.forEach((variable, index) => { if (!envName.test(variable.name) || reservedEnv.has(variable.name) || variable.name.startsWith('SUPABASE_')) context.addIssue({ code: 'custom', path: ['variables', index, 'name'], message: 'Reserved or invalid environment name' }) }))
const port = z.number().int().min(0).max(65535)
const configurationSchema = z.object({ revision: z.number().int().nonnegative(), general: z.object({ domain: z.string(), siteUrl: z.string(), supabaseVersion: z.literal(SUPABASE_VERSION) }), services: serviceSchema, auth: authSchema, storage: storageSchema, realtime: z.object({ maxConnections: z.number().int().min(1).max(100000), databasePoolSize: z.number().int().min(1).max(10000), logLevel: z.enum(['debug', 'info', 'warn', 'error']) }), functions: functionsSchema, database: z.object({ version: z.string(), directPort: z.boolean(), directPortNumber: port, maxConnections: z.number().int().min(1).max(100000), sharedBuffers: z.string(), extensions: z.array(z.string()) }), pooler: z.object({ transactionPort: port, sessionPort: port, poolSize: z.number().int().min(1).max(100000), maxClientConnections: z.number().int().min(1).max(100000) }), network: z.object({ gateway: z.enum(['envoy', 'kong']), httpsMode: z.enum(['external', 'caddy']), internalGatewayPort: port.optional(), apiPort: port, studioPort: port, directDatabasePort: port, poolerPort: port, certificate: z.string().optional() }) }).superRefine((configuration, context) => { const ports: Array<[string, number]> = [['apiPort', configuration.network.apiPort], ['studioPort', configuration.network.studioPort], ['directDatabasePort', configuration.network.directDatabasePort], ['poolerPort', configuration.network.poolerPort], ['transactionPort', configuration.pooler.transactionPort], ['sessionPort', configuration.pooler.sessionPort]]; const seen = new Map<number, string>(); for (const [name, value] of ports) if (value && seen.has(value)) context.addIssue({ code: 'custom', path: ['network', name === 'transactionPort' || name === 'sessionPort' ? 'poolerPort' : name], message: `Port conflicts with ${seen.get(value)}` }); else if (value) seen.set(value, name); if (configuration.services.directDb && (!configuration.database.directPort || !configuration.network.directDatabasePort)) context.addIssue({ code: 'custom', path: ['services', 'directDb'], message: 'Direct DB requires its typed port settings' }); if (configuration.services.supavisor && (!configuration.pooler.transactionPort || !configuration.pooler.sessionPort)) context.addIssue({ code: 'custom', path: ['services', 'supavisor'], message: 'Supavisor requires transaction and session ports' }) })
export const projectConfigurationSchema = configurationSchema.superRefine((configuration, context) => {
  const allowedPhone = configuration.auth.phone.provider === 'twilio' ? ['accountSid', 'messageServiceSid', 'verifySid'] : configuration.auth.phone.provider === 'messagebird' ? ['originator'] : configuration.auth.phone.provider === 'textlocal' ? ['sender'] : []
  for (const key of Object.keys(configuration.auth.phone.fields)) if (!allowedPhone.includes(key)) context.addIssue({ code: 'custom', path: ['auth', 'phone', 'fields', key], message: 'Unsupported provider field' })
  if (!configuration.services.directDb && (configuration.database.directPort || configuration.network.directDatabasePort)) context.addIssue({ code: 'custom', path: ['network', 'directDatabasePort'], message: 'Direct DB port requires the Direct PostgreSQL service' })
})
export type ProjectConfigurationForm = z.infer<typeof projectConfigurationSchema>
export interface ProjectForm { name: string; slug: string; preset: PresetName; configuration: ProjectConfigurationForm }
export const projectSchema = z.object({ name: z.string().trim().min(1, 'Project name is required').max(80), slug: z.string().regex(/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/, 'Use lowercase letters, numbers, and hyphens'), preset: z.enum(PRESETS), configuration: projectConfigurationSchema }).superRefine((project, context) => { if (!project.configuration.general.domain.trim() || !/^([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?::\d+)?$/i.test(project.configuration.general.domain)) context.addIssue({ code: 'custom', path: ['configuration', 'general', 'domain'], message: 'Enter a valid hostname' }); if (!httpUrl().safeParse(project.configuration.general.siteUrl).success) context.addIssue({ code: 'custom', path: ['configuration', 'general', 'siteUrl'], message: 'Enter an http or https URL' }) })
export function applyPreset(preset: Preset): Services { const services = { ...lightweightServices }; if (preset === 'STANDARD' || preset === 'FULL') Object.assign(services, { realtime: true, storage: true, functions: true, supavisor: true }); if (preset === 'FULL') Object.assign(services, { imgproxy: true, logs: true, vector: true }); return services }
const retain = (): { action: SecretAction } => ({ action: 'retain' })
export function defaultConfiguration(preset: PresetName = 'LIGHTWEIGHT'): ProjectConfiguration { return { revision: 0, general: { domain: '', siteUrl: '', supabaseVersion: SUPABASE_VERSION }, services: applyPreset(preset), auth: { enabled: true, jwtExpiry: 0, disableSignup: false, email: { enabled: true, allowSignup: true, confirmEmail: false, secureEmailChange: false, doubleConfirmChanges: false }, phone: { enabled: false, provider: '', secretSet: false, secret: retain(), fields: {} }, anonymousSignIn: false, redirectUrls: [], oauth: {}, smtp: { enabled: false, host: '', port: 587, username: '', passwordSet: false, password: retain(), senderEmail: '', senderName: '' } }, storage: { backend: 'local', s3CompatibleApi: false, bucket: '', region: '', endpoint: '', accountId: '', accessKeyId: '', secretAccessKeySet: false, secretAccessKey: retain(), forcePathStyle: false, localPath: './volumes/storage' }, realtime: { maxConnections: 100, databasePoolSize: 5, logLevel: 'info' }, functions: { defaultJwtVerification: true, directory: './functions', variables: [] }, database: { version: '15', directPort: false, directPortNumber: 0, maxConnections: 100, sharedBuffers: '', extensions: [] }, pooler: { transactionPort: 6543, sessionPort: 6544, poolSize: 20, maxClientConnections: 100 }, network: { gateway: 'envoy', httpsMode: 'external', internalGatewayPort: 0, apiPort: 0, studioPort: 0, directDatabasePort: 0, poolerPort: 0, certificate: '' } } }
export function slugify(value: string) { return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 63) }
export { serviceKeys }
