import { z } from 'zod'
import type { ProjectConfiguration, Preset, Services } from '../../api/types'

export const PRESETS = ['LIGHTWEIGHT', 'STANDARD', 'FULL', 'CUSTOM'] as const
export const SUPABASE_VERSION = 'self-hosted/v0.8.0'
export const OAUTH_PROVIDERS = ['apple','azure','bitbucket','discord','facebook','figma','github','gitlab','google','kakao','keycloak','linkedin_oidc','notion','slack_oidc','snapchat','spotify','twitch','twitter','workos','zoom'] as const
export type OAuthProvider = (typeof OAUTH_PROVIDERS)[number]
export type PresetName = (typeof PRESETS)[number]

export const lightweightServices: Services = { database:true,gateway:true,auth:true,rest:true,studio:true,postgresMeta:true,realtime:false,storage:false,imgproxy:false,functions:false,supavisor:false,logs:false,vector:false,directDb:false }
const serviceSchema = z.object({ database:z.boolean(),gateway:z.boolean(),auth:z.boolean(),rest:z.boolean(),studio:z.boolean(),postgresMeta:z.boolean(),realtime:z.boolean(),storage:z.boolean(),imgproxy:z.boolean(),functions:z.boolean(),supavisor:z.boolean(),logs:z.boolean(),vector:z.boolean(),directDb:z.boolean() }).superRefine((s,c)=>{ if(!s.database)c.addIssue({code:'custom',path:['database'],message:'PostgreSQL is required'}); if(s.studio&&!s.postgresMeta)c.addIssue({code:'custom',path:['postgresMeta'],message:'postgres-meta is required by Studio'}); if(s.imgproxy&&!s.storage)c.addIssue({code:'custom',path:['imgproxy'],message:'Image Transformation requires Storage'}); if(s.vector!==s.logs)c.addIssue({code:'custom',path:['vector'],message:'Logs and Vector must be enabled together'}); if((s.auth||s.rest||s.studio||s.realtime||s.storage)&&!s.gateway)c.addIssue({code:'custom',path:['gateway'],message:'API Gateway is required'}) })
const secretSchema = z.object({ action:z.enum(['retain','replace','remove']).optional(), value:z.string().optional() })
const smtpSchema = z.object({enabled:z.boolean(),host:z.string(),port:z.number().int().min(1).max(65535),username:z.string(),passwordSet:z.boolean(),password:secretSchema,senderEmail:z.string(),senderName:z.string()}).superRefine((s,c)=>{if(!s.enabled)return; for(const [k,v] of [['host',s.host],['username',s.username],['senderName',s.senderName]] as const)if(!v.trim())c.addIssue({code:'custom',path:[k],message:'Required when SMTP is enabled'});if(!z.email().safeParse(s.senderEmail).success)c.addIssue({code:'custom',path:['senderEmail'],message:'Enter a valid email address'});if(!s.passwordSet&&s.password.action!=='replace')c.addIssue({code:'custom',path:['password'],message:'Enter an SMTP password'});if(s.password.action==='remove')c.addIssue({code:'custom',path:['password'],message:'Cannot remove password while SMTP is enabled'})})
const oauthSchema = z.object({enabled:z.boolean(),clientId:z.string(),secretSet:z.boolean(),secret:secretSchema,fields:z.record(z.string(),z.string()).default({})}).superRefine((s,c)=>{if(!s.enabled)return;if(!s.clientId.trim())c.addIssue({code:'custom',path:['clientId'],message:'Required when provider is enabled'});if(!s.secretSet&&s.secret.action!=='replace')c.addIssue({code:'custom',path:['secret'],message:'Enter a client secret'});for(const key of Object.keys(s.fields)){if(!['tenantUrl','enterpriseUrl','selfHostedUrl','realmUrl'].includes(key))c.addIssue({code:'custom',path:['fields',key],message:'Unsupported provider field'});if(key==='tenantUrl'||key==='realmUrl'||key==='enterpriseUrl'||key==='selfHostedUrl')if(s.fields[key]&&!z.url().safeParse(s.fields[key]).success)c.addIssue({code:'custom',path:['fields',key],message:'Enter an absolute URL'})}})
const storageSchema = z.object({backend:z.enum(['local','s3','aws-s3','r2']),s3CompatibleApi:z.boolean(),bucket:z.string(),region:z.string(),endpoint:z.string(),accountId:z.string(),accessKeyId:z.string(),secretAccessKeySet:z.boolean(),secretAccessKey:secretSchema,forcePathStyle:z.boolean(),localPath:z.string()}).superRefine((s,c)=>{if(s.backend==='local'){if(s.bucket||s.region||s.endpoint||s.accountId||s.accessKeyId||s.secretAccessKeySet)c.addIssue({code:'custom',path:['backend'],message:'Local storage cannot include object-storage credentials'});return}if(!s.bucket.trim())c.addIssue({code:'custom',path:['bucket'],message:'Bucket is required'});if(s.backend!=='r2'&&!s.region.trim())c.addIssue({code:'custom',path:['region'],message:'Region is required'});if(!s.accessKeyId.trim())c.addIssue({code:'custom',path:['accessKeyId'],message:'Access key is required'});if(!s.secretAccessKeySet&&s.secretAccessKey.action!=='replace')c.addIssue({code:'custom',path:['secretAccessKey'],message:'Enter a secret access key'});if(s.backend==='r2'&&!s.accountId.trim())c.addIssue({code:'custom',path:['accountId'],message:'Account ID is required'});if(s.backend==='r2'&&s.endpoint)c.addIssue({code:'custom',path:['endpoint'],message:'R2 endpoint is derived from accountId'});if(s.backend==='s3'&&!s.endpoint.trim())c.addIssue({code:'custom',path:['endpoint'],message:'Endpoint is required'});if(s.endpoint&&!z.url().safeParse(s.endpoint).success)c.addIssue({code:'custom',path:['endpoint'],message:'Enter an absolute URL'})})
const envName=/^[A-Z_][A-Z0-9_]*$/;const reservedEnv=new Set(['ANON_KEY','SERVICE_ROLE_KEY','JWT_SECRET','SUPABASE_URL','SUPABASE_PUBLIC_URL','FUNCTIONS_VERIFY_JWT','POSTGRES_PASSWORD'])
const functionsSchema=z.object({defaultJwtVerification:z.boolean(),directory:z.string(),variables:z.array(z.object({name:z.string(),valueSet:z.boolean(),value:secretSchema})).default([])}).superRefine((f,c)=>f.variables.forEach((v,i)=>{if(!envName.test(v.name)||reservedEnv.has(v.name)||v.name.startsWith('SUPABASE_'))c.addIssue({code:'custom',path:['variables',i,'name'],message:'Reserved or invalid environment name'})}))
const authSchema=z.object({enabled:z.boolean(),jwtExpiry:z.number().int().min(0).max(31536000),disableSignup:z.boolean(),email:z.object({enabled:z.boolean(),allowSignup:z.boolean(),confirmEmail:z.boolean(),secureEmailChange:z.boolean(),doubleConfirmChanges:z.boolean()}),phone:z.object({enabled:z.boolean(),provider:z.string(),secretSet:z.boolean(),secret:secretSchema,fields:z.record(z.string(),z.string()).default({})}),anonymousSignIn:z.boolean(),redirectUrls:z.array(z.string().refine(v=>z.url().safeParse(v).success&&/^https?:/.test(v),'Enter an http or https URL')),oauth:z.record(z.string(),oauthSchema).default({}),smtp:smtpSchema}).superRefine((a,c)=>{if(a.disableSignup!==!a.email.allowSignup)c.addIssue({code:'custom',path:['disableSignup'],message:'Must match email signup policy'});if(a.email.secureEmailChange!==a.email.doubleConfirmChanges)c.addIssue({code:'custom',path:['email','secureEmailChange'],message:'Must match double confirmation'})})
const strictAuthSchema=authSchema.superRefine((a,c)=>Object.entries(a.oauth).forEach(([provider,value])=>{const required=provider==='azure'?'tenantUrl':provider==='keycloak'?'realmUrl':undefined;if(required&&!value.fields[required]?.trim())c.addIssue({code:'custom',path:['oauth',provider,'fields',required],message:'Required for this provider'});for(const key of Object.keys(value.fields))if(!(['azure','github','gitlab','keycloak'].includes(provider)&&['tenantUrl','enterpriseUrl','selfHostedUrl','realmUrl'].includes(key)))c.addIssue({code:'custom',path:['oauth',provider,'fields',key],message:'Unsupported provider field'})}))
export const projectConfigurationSchema=z.object({revision:z.number().int().nonnegative(),general:z.object({domain:z.string().refine(v=>v===''||v==='localhost'||/^[a-z0-9.-]+(?::\d+)?$/.test(v),'Enter a hostname without a scheme'),siteUrl:z.string().refine(v=>v===''||(z.url().safeParse(v).success&&/^https?:/.test(v)),'Enter an http or https URL'),supabaseVersion:z.string().refine(v=>v===SUPABASE_VERSION,'Unsupported pinned version')}),services:serviceSchema,auth:strictAuthSchema,storage:storageSchema,realtime:z.object({maxConnections:z.number().int().min(1).max(100000),databasePoolSize:z.number().int().min(1).max(10000),logLevel:z.enum(['debug','info','warn','error'])}),functions:functionsSchema,database:z.object({version:z.string(),directPort:z.boolean(),directPortNumber:z.number().int().min(0).max(65535),maxConnections:z.number().int().min(1).max(100000),sharedBuffers:z.string(),extensions:z.array(z.string())}),pooler:z.object({transactionPort:z.number().int().min(0).max(65535),sessionPort:z.number().int().min(0).max(65535),poolSize:z.number().int().min(1).max(100000),maxClientConnections:z.number().int().min(1).max(100000)}),network:z.object({gateway:z.enum(['envoy','kong']),httpsMode:z.enum(['external','caddy','manual']),internalGatewayPort:z.number().int().min(0).max(65535),apiPort:z.number().int().min(0).max(65535),studioPort:z.number().int().min(0).max(65535),directDatabasePort:z.number().int().min(0).max(65535),poolerPort:z.number().int().min(0).max(65535),certificate:z.string()})})
export type ProjectConfigurationForm=z.infer<typeof projectConfigurationSchema>
export interface ProjectForm { name:string; slug:string; preset:PresetName; configuration:ProjectConfigurationForm }
export const projectSchema = z.object({ name:z.string().trim().min(1).max(80), slug:z.string().regex(/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/,'Use lowercase letters, numbers, and hyphens'), preset:z.enum(PRESETS), configuration:projectConfigurationSchema }).superRefine((v,c)=>{if(!v.configuration.general.domain.trim()&&v.configuration.general.domain!=='localhost')c.addIssue({code:'custom',path:['configuration','general','domain'],message:'Enter a hostname'});if(!z.url().safeParse(v.configuration.general.siteUrl).success||!/^https?:/.test(v.configuration.general.siteUrl))c.addIssue({code:'custom',path:['configuration','general','siteUrl'],message:'Enter an http or https URL'})})
export function applyPreset(preset:Preset):Services{const s={...lightweightServices};if(preset==='STANDARD'||preset==='FULL')Object.assign(s,{realtime:true,storage:true,functions:true,supavisor:true});if(preset==='FULL')Object.assign(s,{imgproxy:true,logs:true,vector:true});return s}
export function defaultConfiguration(preset:PresetName='LIGHTWEIGHT'):ProjectConfiguration{return {revision:0,general:{domain:'',siteUrl:'',supabaseVersion:SUPABASE_VERSION},services:applyPreset(preset),auth:{enabled:true,jwtExpiry:0,disableSignup:false,email:{enabled:true,allowSignup:true,confirmEmail:false,secureEmailChange:false,doubleConfirmChanges:false},phone:{enabled:false,provider:'',secretSet:false,secret:{},fields:{}},anonymousSignIn:false,redirectUrls:[],oauth:{},smtp:{enabled:false,host:'',port:587,username:'',passwordSet:false,password:{},senderEmail:'',senderName:''}},storage:{backend:'local',s3CompatibleApi:false,bucket:'',region:'',endpoint:'',accountId:'',accessKeyId:'',secretAccessKeySet:false,secretAccessKey:{},forcePathStyle:false,localPath:''},realtime:{maxConnections:100,databasePoolSize:5,logLevel:'info'},functions:{defaultJwtVerification:true,directory:'./functions',variables:[]},database:{version:'15',directPort:false,directPortNumber:0,maxConnections:100,sharedBuffers:'',extensions:[]},pooler:{transactionPort:6543,sessionPort:6544,poolSize:20,maxClientConnections:100},network:{gateway:'envoy',httpsMode:'external',internalGatewayPort:0,apiPort:0,studioPort:0,directDatabasePort:0,poolerPort:0,certificate:''}}}
export function slugify(value:string){return value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,63)}
