import type { UseFormReturn } from 'react-hook-form'
import { Alert } from '@/components/ui/alert'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Switch } from '@/components/ui/switch'
import { Textarea } from '@/components/ui/textarea'
import type { ProjectForm } from './projectSchema'
import { setServiceEnabled } from './PresetStep'

export function StorageFunctionsStep({ form }: { form: UseFormReturn<ProjectForm> }) {
  const storage = form.watch('configuration.storage'); const services = form.watch('configuration.services'); const functions = form.watch('configuration.functions');
  const set = (name: string, value: unknown) => { form.setValue(name as any, value as any, { shouldDirty: true, shouldValidate: true }); form.setValue('preset', 'CUSTOM', { shouldDirty: true }) }
  const error = (name: string) => { let value: any = form.formState.errors; for (const part of name.split('.')) value = value?.[part]; return value?.message as string | undefined }
  const setBackend = (backend: string) => { const base = form.getValues('configuration.storage'); const clean = backend === 'local' ? { ...base, backend, bucket: '', region: '', endpoint: '', accountId: '', accessKeyId: '', secretAccessKeySet: false, secretAccessKey: { action: 'retain' as const }, forcePathStyle: false } : { ...base, backend, endpoint: backend === 'r2' || backend === 'aws-s3' ? '' : base.endpoint, accountId: backend === 'r2' ? base.accountId : '' }; set('configuration.storage', clean) }
  const variablesText = functions.variables.map((variable) => `${variable.name}=`).join('\n')
  return <Card><CardHeader><CardTitle>Storage & Functions</CardTitle><CardDescription>Backend credentials are write-only; service changes also reconcile their dependencies.</CardDescription></CardHeader><CardContent className="space-y-7">
    <Field orientation="horizontal" className="items-center justify-between rounded-lg border border-border px-3 py-2"><FieldLabel>Storage service</FieldLabel><Switch checked={services.storage} onCheckedChange={(enabled) => setServiceEnabled(form, 'storage', enabled)} /></Field>
    <Field orientation="horizontal" className="items-center justify-between rounded-lg border border-border px-3 py-2"><FieldLabel>S3-compatible API</FieldLabel><Switch checked={storage.s3CompatibleApi} onCheckedChange={(enabled) => set('configuration.storage.s3CompatibleApi', enabled)} /></Field>
    {services.storage && <section className="space-y-4"><Field><FieldLabel>Storage backend</FieldLabel><Select value={storage.backend} onValueChange={(value) => { if (value) setBackend(value) }}><SelectTrigger aria-label="Storage backend"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="local">Local filesystem</SelectItem><SelectItem value="aws-s3">AWS S3</SelectItem><SelectItem value="r2">Cloudflare R2</SelectItem><SelectItem value="s3">Custom S3-compatible</SelectItem></SelectContent></Select><FieldError>{error('configuration.storage.backend')}</FieldError></Field>{storage.backend === 'local' ? <Alert>Local storage uses the managed path <code>{storage.localPath}</code>. Object-storage fields are cleared when switching back to Local.</Alert> : <><FieldGroup className="grid gap-4 md:grid-cols-2"><TextField label="Bucket" name="configuration.storage.bucket" form={form} error={error('configuration.storage.bucket')} /><TextField label="Region" name="configuration.storage.region" form={form} error={error('configuration.storage.region')} />{storage.backend === 'r2' ? <TextField label="Account ID" name="configuration.storage.accountId" form={form} error={error('configuration.storage.accountId')} /> : <TextField label="Endpoint" name="configuration.storage.endpoint" form={form} error={error('configuration.storage.endpoint')} />}<TextField label="Access key ID" name="configuration.storage.accessKeyId" form={form} error={error('configuration.storage.accessKeyId')} /><Field><FieldLabel htmlFor="storage-secret">Secret access key</FieldLabel><Input id="storage-secret" type="password" placeholder={storage.secretAccessKeySet ? 'Configured — enter to replace' : ''} onChange={(event) => set('configuration.storage.secretAccessKey', event.target.value ? { action: 'replace', value: event.target.value } : { action: 'retain' })} aria-invalid={!!error('configuration.storage.secretAccessKey')} /><FieldError>{error('configuration.storage.secretAccessKey')}</FieldError></Field></FieldGroup><Field orientation="horizontal" className="items-center justify-between rounded-lg border border-border px-3 py-2"><FieldLabel>Force path style</FieldLabel><Switch checked={storage.forcePathStyle} onCheckedChange={(enabled) => set('configuration.storage.forcePathStyle', enabled)} /></Field></>}</section>}
    <section className="space-y-4"><div className="flex items-center justify-between"><div><h3 className="font-medium">Edge Functions</h3><p className="text-sm text-muted-foreground">Typed runtime and secret environment variables.</p></div><Switch aria-label="Enable Functions" checked={services.functions} onCheckedChange={(enabled) => setServiceEnabled(form, 'functions', enabled)} /></div>{services.functions && <Collapsible defaultOpen><CollapsibleTrigger className="text-sm font-medium underline">Advanced Functions settings</CollapsibleTrigger><CollapsibleContent className="mt-4 space-y-4"><Field><FieldLabel>Functions directory</FieldLabel><Input readOnly value={functions.directory} /></Field><Field orientation="horizontal" className="items-center justify-between rounded-lg border border-border px-3 py-2"><FieldLabel>Verify JWT by default</FieldLabel><Switch checked={functions.defaultJwtVerification} onCheckedChange={(enabled) => set('configuration.functions.defaultJwtVerification', enabled)} /></Field><Field><FieldLabel htmlFor="function-variables">Environment variables</FieldLabel><FieldDescription>Enter NAME=value lines. Existing values remain write-only when left blank.</FieldDescription><Textarea id="function-variables" value={variablesText} onChange={(event) => { const variables = event.target.value.split(/\n/).filter(Boolean).map((line) => { const index = line.indexOf('='); const name = (index < 0 ? line : line.slice(0, index)).trim(); const value = index < 0 ? '' : line.slice(index + 1); const existing = functions.variables.find((variable) => variable.name === name); return { name, valueSet: value ? true : !!existing?.valueSet, value: value ? { action: 'replace' as const, value } : existing?.valueSet ? existing.value : { action: 'retain' as const } } }); set('configuration.functions.variables', variables) }} aria-invalid={!!error('configuration.functions.variables')} /><FieldError>{error('configuration.functions.variables')}</FieldError></Field></CollapsibleContent></Collapsible>}</section>
    <Field orientation="horizontal" className="items-center justify-between rounded-lg border border-border px-3 py-2"><FieldLabel>Image transformation (requires Storage)</FieldLabel><Switch checked={services.imgproxy} disabled={!services.storage} onCheckedChange={(enabled) => setServiceEnabled(form, 'imgproxy', enabled)} /></Field>
  </CardContent></Card>
}
function TextField({ label, name, form, error }: { label: string; name: string; form: UseFormReturn<ProjectForm>; error?: string }) { return <Field><FieldLabel htmlFor={name}>{label}</FieldLabel><Input id={name} {...form.register(name as any)} aria-invalid={!!error} /><FieldError>{error}</FieldError></Field> }
