import { zodResolver } from '@hookform/resolvers/zod'
import { useEffect } from 'react'
import { useForm, type Resolver, type UseFormReturn } from 'react-hook-form'
import type { AuthConfig } from '../../../api/types'
import { authSchema } from './schema'
import { SectionCard, Toggle, TextField, NumberField, SecretEditor, SectionSaveButton } from './fields'

export function AuthSection({ initial, onSave }: { initial: AuthConfig; onSave: (value: AuthConfig, dirty: unknown) => void }) {
  const form = useForm<AuthConfig>({ resolver: zodResolver(authSchema) as Resolver<AuthConfig>, defaultValues: initial })
  useEffect(() => { form.reset(initial) }, [initial, form])
  const auth = form.watch()
  return <form id="configuration-auth-form" onSubmit={form.handleSubmit((value) => onSave(value, form.formState.dirtyFields))} className="space-y-5"><SectionCard title="Authentication" description="Auth policy, signup/session controls, redirects and phone authentication."><div className="grid gap-3 md:grid-cols-2"><div className="rounded-lg border border-border p-3"><p className="text-sm font-medium">Auth service</p><p className="mt-1 text-xs text-muted-foreground">Enablement is owned by Services.</p></div><Toggle id="email-auth" label="Email Auth" checked={auth.email.enabled} onChange={(value) => form.setValue('email.enabled', value, { shouldDirty: true, shouldValidate: true })} /><Toggle id="allow-signup" label="Allow signup" checked={auth.email.allowSignup} onChange={(value) => { form.setValue('email.allowSignup', value, { shouldDirty: true, shouldValidate: true }); form.setValue('disableSignup', !value, { shouldDirty: true, shouldValidate: true }) }} /><Toggle id="confirm-email" label="Confirm email" checked={auth.email.confirmEmail} onChange={(value) => form.setValue('email.confirmEmail', value, { shouldDirty: true, shouldValidate: true })} /><Toggle id="secure-email-change" label="Secure email change" checked={auth.email.secureEmailChange} onChange={(value) => { form.setValue('email.secureEmailChange', value, { shouldDirty: true, shouldValidate: true }); form.setValue('email.doubleConfirmChanges', value, { shouldDirty: true, shouldValidate: true }) }} /><Toggle id="anonymous-sign-in" label="Anonymous sign-in" checked={auth.anonymousSignIn} onChange={(value) => form.setValue('anonymousSignIn', value, { shouldDirty: true, shouldValidate: true })} /><NumberField form={form} name="jwtExpiry" label="JWT expiry (seconds)" min={0} max={31536000} /></div><label htmlFor="auth-redirect-urls" className="text-sm font-medium">Redirect URLs</label><textarea id="auth-redirect-urls" className="min-h-24 w-full rounded-md border bg-background px-3 py-2 text-sm" value={auth.redirectUrls.join('\n')} onChange={(event) => form.setValue('redirectUrls', event.target.value.split(/\n/).map((value) => value.trim()).filter(Boolean), { shouldDirty: true, shouldValidate: true })} /><PhoneFields form={form} /></SectionCard><SectionSaveButton label="Authentication" disabled={!form.formState.isDirty} /></form>
}

function PhoneFields({ form }: { form: UseFormReturn<AuthConfig> }) {
  const phone = form.watch('phone')
  const allowed = phone.provider === 'twilio' ? [['accountSid', 'Account SID'], ['messageServiceSid', 'Message Service SID'], ['verifySid', 'Verify SID']] : phone.provider === 'messagebird' ? [['originator', 'Originator']] : phone.provider === 'textlocal' ? [['sender', 'Sender']] : []
  return <fieldset className="space-y-4 rounded-lg border border-border p-4"><legend className="px-1 text-sm font-semibold">Phone Auth</legend><Toggle id="phone-auth" label="Enable Phone Auth" checked={phone.enabled} onChange={(value) => form.setValue('phone.enabled', value, { shouldDirty: true, shouldValidate: true })} /><div><label htmlFor="phone-provider" className="text-sm font-medium">Provider</label><select id="phone-provider" className="mt-1 h-9 w-full rounded-md border bg-background px-3 text-sm" value={phone.provider} onChange={(event) => form.setValue('phone.provider', event.target.value, { shouldDirty: true, shouldValidate: true })}><option value="">Choose provider</option><option value="twilio">Twilio</option><option value="messagebird">MessageBird</option><option value="textlocal">Textlocal</option></select></div>{phone.enabled && <div className="grid gap-4 md:grid-cols-2">{allowed.map(([name, label]) => <TextField key={name} form={form} name={`phone.fields.${name}` as 'phone.fields'} label={label} />)}<SecretEditor label="Provider secret" configured={phone.secretSet} secret={phone.secret} onChange={(value) => form.setValue('phone.secret', value, { shouldDirty: true, shouldValidate: true })} /></div>}</fieldset>
}
