import { zodResolver } from '@hookform/resolvers/zod'
import { useEffect } from 'react'
import { useForm, type Resolver } from 'react-hook-form'
import type { FunctionVariable, FunctionsConfig } from '../../../api/types'
import { functionsSchema } from './schema'
import { SectionCard, Toggle, TextField, SecretEditor, ReadOnlyField, SectionSaveButton } from './fields'

export function FunctionsSection({ initial, enabled, onSave }: { initial: FunctionsConfig; enabled: boolean; onSave: (value: FunctionsConfig, dirty: unknown) => void }) {
  const form = useForm<FunctionsConfig>({ resolver: zodResolver(functionsSchema) as Resolver<FunctionsConfig>, defaultValues: initial }); useEffect(() => { form.reset(initial) }, [initial, form])
  const functions = form.watch(); const variables = functions.variables ?? []
  const updateVariables = (next: FunctionVariable[]) => form.setValue('variables', next, { shouldDirty: true, shouldValidate: true })
  return <form id="configuration-functions-form" onSubmit={form.handleSubmit((value) => onSave(value, form.formState.dirtyFields))} className="space-y-5"><SectionCard title="Functions" description="Environment values are encrypted and rendered into the Functions runtime. Deleting a configured variable explicitly removes its secret."><p className="text-sm text-muted-foreground">Functions service is currently <strong>{enabled ? 'enabled' : 'disabled'}</strong>; enablement is owned by Services.</p><Toggle id="functions-jwt" label="Default JWT verification" checked={functions.defaultJwtVerification} onChange={(value) => form.setValue('defaultJwtVerification', value, { shouldDirty: true, shouldValidate: true })} /><ReadOnlyField label="Functions directory" value={functions.directory} /><div className="space-y-3"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Environment variables</h3><button type="button" className="rounded-md border px-3 py-1.5 text-sm" onClick={() => updateVariables([...variables, { name: '', valueSet: false, value: { action: '' } }])}>Add variable</button></div>{variables.map((item, index) => <div className="grid items-end gap-2 md:grid-cols-[1fr_1fr_auto]" key={`${index}-${item.name}`}><TextField form={form} name={`variables.${index}.name` as 'variables'} label="Name" /><SecretEditor label={`Value for ${item.name || `variable ${index + 1}`}`} configured={item.valueSet} secret={item.value} onChange={(value) => { const next = [...variables]; next[index] = { ...next[index], value }; form.setValue('variables', next, { shouldDirty: true, shouldValidate: true }) }} /><button type="button" className="rounded-md border px-3 py-2 text-sm" onClick={() => { if (item.valueSet) { const next = [...variables]; next[index] = { ...next[index], value: { action: 'remove' } }; updateVariables(next) } else updateVariables(variables.filter((_, current) => current !== index)) }} aria-label={`Remove variable ${item.name || index + 1}`}>Remove</button></div>)}</div></SectionCard><SectionSaveButton label="Functions" disabled={!form.formState.isDirty} /></form>
}
