import { zodResolver } from '@hookform/resolvers/zod'
import { useForm, type Resolver } from 'react-hook-form'
import type { FunctionVariable, FunctionsConfig } from '../../../api/types'
import { Button } from '@/components/ui/button'
import { functionsSchema } from './schema'
import { SectionCard, Toggle, TextField, SecretEditor, SectionSaveButton, useResetOnServerRevision, type SectionSave } from './fields'

export function FunctionsSection({ initial, revision, enabled, onSave }: { initial: FunctionsConfig; revision: number; enabled: boolean; onSave: SectionSave<FunctionsConfig> }) {
  const form = useForm<FunctionsConfig>({ resolver: zodResolver(functionsSchema) as Resolver<FunctionsConfig>, defaultValues: initial }); useResetOnServerRevision(form, initial, revision)
  const functions = form.watch(); const variables = functions.variables ?? []
  const updateVariables = (next: FunctionVariable[]) => form.setValue('variables', next, { shouldDirty: true, shouldValidate: true })
  const setError = (name: string, message: string) => form.setError(name as never, { type: 'server', message })
  return <form id="configuration-functions-form" onSubmit={form.handleSubmit((value) => onSave({ value, dirty: form.formState.dirtyFields, setError }))} className="space-y-5"><SectionCard title="Functions" description="Environment values are encrypted and rendered into the Functions runtime. Deleting a configured variable explicitly removes its secret."><p className="text-sm text-muted-foreground">Functions service is currently <strong>{enabled ? 'enabled' : 'disabled'}</strong>; enablement is owned by Services.</p><Toggle id="functions-jwt" label="Default JWT verification" checked={functions.defaultJwtVerification} onChange={(value) => form.setValue('defaultJwtVerification', value, { shouldDirty: true, shouldValidate: true })} /><div className="space-y-3"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Environment variables</h3><Button type="button" variant="outline" onClick={() => updateVariables([...variables, { name: '', valueSet: false, value: { action: '' } }])}>Add variable</Button></div>{variables.map((item, index) => <div className="space-y-2" key={`${index}-${item.name}`}><TextField form={form} name={`variables.${index}.name` as 'variables'} label="Name" /><SecretEditor label={`Value for ${item.name || `variable ${index + 1}`}`} configured={item.valueSet} secret={item.value} onChange={(value) => { const next = [...variables]; next[index] = { ...next[index], value }; form.setValue('variables', next, { shouldDirty: true, shouldValidate: true }) }} /><Button type="button" variant="outline" onClick={() => { if (item.valueSet) { const next = [...variables]; next[index] = { ...next[index], value: { action: 'remove' } }; updateVariables(next) } else updateVariables(variables.filter((_, current) => current !== index)) }} aria-label={`Remove variable ${item.name || index + 1}`}>Remove</Button></div>)}</div></SectionCard><SectionSaveButton label="Functions" disabled={!form.formState.isDirty} /></form>
}
