import { zodResolver } from '@hookform/resolvers/zod'
import { useForm, type Resolver } from 'react-hook-form'
import type { NetworkConfig } from '../../../api/types'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { networkSchema } from './schema'
import { SectionCard, ReadOnlyField, SectionSaveButton, useResetOnServerRevision } from './fields'
export function NetworkSection({ initial, revision, onSave }: { initial: NetworkConfig; revision: number; onSave: (value: NetworkConfig, dirty: unknown) => void }) {
  const form = useForm<NetworkConfig>({ resolver: zodResolver(networkSchema) as Resolver<NetworkConfig>, defaultValues: initial }); useResetOnServerRevision(form, initial, revision); const network = form.watch()
  return <form id="configuration-network-form" onSubmit={form.handleSubmit((value) => onSave(value, form.formState.dirtyFields))} className="space-y-5"><SectionCard title="Gateway & Network" description="Gateway selection and HTTPS mode are typed. Manager-allocated ports are read-only."><div className="grid gap-4 md:grid-cols-2"><div><label htmlFor="network-gateway" className="text-sm font-medium">Gateway</label><Select value={network.gateway} onValueChange={(value) => form.setValue('gateway', value as NetworkConfig['gateway'], { shouldDirty: true, shouldValidate: true })}><SelectTrigger id="network-gateway" aria-label="Gateway" className="mt-1 w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="envoy">Envoy (recommended)</SelectItem><SelectItem value="kong">Kong (advanced)</SelectItem></SelectContent></Select></div><div><label htmlFor="network-https-mode" className="text-sm font-medium">HTTPS mode</label><Select value={network.httpsMode} onValueChange={(value) => form.setValue('httpsMode', value as NetworkConfig['httpsMode'], { shouldDirty: true, shouldValidate: true })}><SelectTrigger id="network-https-mode" aria-label="HTTPS mode" className="mt-1 w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="external">External reverse proxy</SelectItem><SelectItem value="caddy">Caddy managed</SelectItem></SelectContent></Select></div><ReadOnlyField label="API port" value={String(network.apiPort || 'Manager allocated')} /><ReadOnlyField label="Studio port" value={String(network.studioPort || 'Manager allocated')} /><ReadOnlyField label="Direct database port" value={String(network.directDatabasePort || 'Disabled')} /><ReadOnlyField label="Pooler port" value={String(network.poolerPort || 'Manager allocated')} /></div></SectionCard><SectionSaveButton label="Gateway & Network" disabled={!form.formState.isDirty} /></form>
}
