import { zodResolver } from '@hookform/resolvers/zod'
import { useForm, type Resolver } from 'react-hook-form'
import type { RealtimeConfig } from '../../../api/types'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { realtimeSchema } from './schema'
import { SectionCard, NumberField, SectionSaveButton, useResetOnServerRevision, errorAt, type SectionSave } from './fields'

export function RealtimeSection({ initial, revision, enabled, onSave }: { initial: RealtimeConfig; revision: number; enabled: boolean; onSave: SectionSave<RealtimeConfig> }) {
  const form = useForm<RealtimeConfig>({ resolver: zodResolver(realtimeSchema) as Resolver<RealtimeConfig>, defaultValues: initial }); useResetOnServerRevision(form, initial, revision)
  const setError = (name: string, message: string) => form.setError(name as never, { type: 'server', message }); const levelError = errorAt(form.formState.errors, 'logLevel')
  return <form id="configuration-realtime-form" onSubmit={form.handleSubmit((value) => onSave({ value, dirty: form.formState.dirtyFields, setError }))} className="space-y-5"><SectionCard title="Realtime" description="Realtime enablement is owned by Services. Values are bounded and typed."><p className="text-sm text-muted-foreground">Realtime service is currently <strong>{enabled ? 'enabled' : 'disabled'}.</strong></p><div className="grid gap-4 md:grid-cols-2"><NumberField form={form} name="maxConnections" label="Maximum connections" min={1} max={100000} /><NumberField form={form} name="databasePoolSize" label="Database pool size" min={1} max={10000} /><div><label htmlFor="realtime-log-level" className="text-sm font-medium">Log level</label><Select value={form.watch('logLevel')} onValueChange={(value) => form.setValue('logLevel', value as RealtimeConfig['logLevel'], { shouldDirty: true, shouldValidate: true })}><SelectTrigger id="realtime-log-level" aria-label="Realtime log level" aria-invalid={Boolean(levelError)} aria-describedby={levelError ? 'realtime-log-level-error' : undefined} className="mt-1 w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="debug">debug</SelectItem><SelectItem value="info">info</SelectItem><SelectItem value="warn">warn</SelectItem><SelectItem value="error">error</SelectItem></SelectContent></Select>{levelError && <p id="realtime-log-level-error" className="text-sm text-destructive">{levelError}</p>}</div></div></SectionCard><SectionSaveButton label="Realtime" disabled={!form.formState.isDirty} /></form>
}
