import { useEffect, useState } from 'react'
import { AlertTriangle, Copy, Eye, EyeOff } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Alert } from '@/components/ui/alert'
import { SectionCard, ReadOnlyField } from './fields'
import { APIError, apiFetch } from '../../../api/client'

const kinds = ['anonKey', 'serviceRoleKey', 'jwtSecret', 'databasePassword'] as const
type Kind = typeof kinds[number]
export function SecretsSection({ projectId, projectUrl }: { projectId: string; projectUrl: string; anonKey?: string }) {
  const [values, setValues] = useState<Partial<Record<Kind, string>>>({}); const [open, setOpen] = useState(false); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState<Kind | undefined>()
  useEffect(() => () => setValues({}), [])
  const reveal = async (kind: Kind) => { setBusy(kind); setError(''); try { const result = await apiFetch<{ value: string }>(`/api/projects/${projectId}/secrets/${kind}/reveal`, { method: 'POST', body: JSON.stringify({ password }) }); setValues((current) => ({ ...current, [kind]: result.value })); window.setTimeout(() => setValues((current) => { const next = { ...current }; delete next[kind]; return next }), 60_000) } catch (caught) { setError(caught instanceof APIError ? caught.message : 'Unable to reveal secret') } finally { setBusy(undefined) } }
  const copy = async (kind: Kind) => { if (values[kind]) await navigator.clipboard?.writeText(values[kind] as string) }
  return <SectionCard title="API & Secrets" description="Server URL is public. Anon Key and all sensitive values require recent administrator authentication and never appear in configuration responses."><ReadOnlyField label="Server URL" value={projectUrl || 'Unavailable'} copy={Boolean(projectUrl)} /><div className="rounded-lg border border-border p-4"><div className="flex items-center gap-2"><AlertTriangle className="size-4 text-amber-500" /><strong className="text-sm">Public and sensitive values</strong></div><p className="mt-2 text-sm text-muted-foreground">Anon Key, Service Role Key, JWT Secret, and Database Password are revealed only after password confirmation. Values stay in memory and clear after 60 seconds.</p><Button type="button" variant="outline" className="mt-3" onClick={() => { setOpen((current) => !current); setPassword(''); setError('') }}><Eye className="size-4" />{open ? 'Hide reveal controls' : 'Reveal API keys and secrets'}</Button>{open && <div className="mt-4 space-y-3"><label htmlFor="reveal-password" className="text-sm font-medium">Administrator password</label><Input id="reveal-password" type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} />{error && <Alert variant="destructive">{error}</Alert>}{kinds.map((kind) => <div key={kind} className="flex items-center justify-between gap-2"><span className="text-sm">{kind}</span>{values[kind] ? <><code className="max-w-[260px] truncate">{values[kind]}</code><Button type="button" size="icon" variant="outline" aria-label={`Copy ${kind}`} onClick={() => void copy(kind)}><Copy /></Button><Button type="button" size="icon" variant="outline" aria-label={`Hide ${kind}`} onClick={() => setValues((current) => { const next = { ...current }; delete next[kind]; return next })}><EyeOff /></Button></> : <Button type="button" size="sm" variant="outline" disabled={!password || Boolean(busy)} onClick={() => void reveal(kind)}>{busy === kind ? 'Revealing…' : `Reveal ${kind}`}</Button>}</div>)}</div>}</div></SectionCard>
}
